In [1]:
# -*- coding:utf-8 -*-
import pandas as pd
import codecs
import json
import io
import StringIO
from pandas.io.json import json_normalize
import datetime

def readLogicPay():
    with open('/Users/tq/Downloads/logics_pay.10.11.2016.log', 'r') as json_data:
        json_buffer = StringIO.StringIO()
        for line in json_data:
            tempMap = {}
            json_dicts = json.loads(line)  # 读取json数据为list[dict]结构
            tempMap.setdefault('gid', json_dicts['gid'])
            #tempMap.setdefault('acid', json_dicts['accountid'])
            tempMap.setdefault('Money', json_dicts['info']['Money'])
            tempMap.setdefault('PayTime', json_dicts['utc8'][0:10])
            tempMap.setdefault('uid',json_dicts['userid'])
            json_temp = json.dumps(tempMap)
            json_buffer.writelines(json_temp + "\n")

    pay = pd.read_json(json_buffer.getvalue(), lines=True)
    return pay


def getUidTemp():
    uidBygid = pd.read_json('/Users/tq/Downloads/uid_creatTime.json')
    uid_temp = uidBygid[['uid', 'date', 'gid']]
    return uid_temp
    
def getUidByGidPeopleCount(uid_temp):
    creatGroup = uid_temp.groupby([uid_temp['date'], uid_temp['gid']]).count()
    creatGroup.rename(columns={'uid': 'peopleCount'}, inplace=True)
    creatGroup.reset_index(inplace=True)
    return creatGroup

def getSumTemp(payMerge):
    data2 = payMerge.reset_index()
    data3 = data2.set_index(["gid", "date", "PayTime"])   # index is the new column created by reset_index
    running_sum = data3.groupby(level=[0,1,2]).sum().groupby(level=[0,1]).cumsum() 
#     result = payMerge.groupby([payMerge['sid'], payMerge['date'], payMerge['PayTime']]).sum()
    del running_sum['index']
    temp_sum = running_sum.reset_index()
    return temp_sum

if __name__ == '__main__':
    summaryInfo = {}
    pay = readLogicPay()
    uid_temp = getUidTemp()
    creatGroup = getUidByGidPeopleCount(uid_temp)
    
    payMerge = pay.merge(uid_temp, left_on='uid', right_on='uid', how='left',suffixes=['', '_r'])
    del payMerge['gid_r']
    
    temp_sum = getSumTemp(payMerge)
    finalpayMerge = pd.merge(temp_sum, creatGroup, on=['gid', 'date'], how='left', suffixes=['', '_r'])
    finalpayMerge['consume'] = finalpayMerge.Money / finalpayMerge.peopleCount
    #finalpayMerge['day'] = (finalpayMerge['PayTime'].apply(lambda x: x.date())) - finalpayMerge['date'].apply(lambda x: x.date())
    #finalpayMerge['day'] = finalpayMerge['day'].apply(lambda x: x.days)
    del finalpayMerge['PayTime']

In [13]:
    dd = payMerge.groupby(['gid','date','PayTime']).sum()
    dd.reset_index(inplace=True)

In [23]:
    cc = pd.merge(dd, creatGroup, on=['gid', 'date'], how='left', suffixes=['', '_r'])

In [24]:
    cc

    gid       date     PayTime   Money  peopleCount
0   200 2016-11-10  1970-01-01     172        58436
1   200 2016-11-10  2016-11-02     865        58436
2   200 2016-11-10  2016-11-04      49        58436
3   200 2016-11-10  2016-11-05      18        58436
4   200 2016-11-10  2016-11-07      31        58436
5   200 2016-11-10  2016-11-08       8        58436
6   200 2016-11-10  2016-11-09       4        58436
7   200 2016-11-10  2016-11-10  416759        58436
8   200 2016-11-10  2016-11-11  181275        58436
9   200 2016-11-10  2016-11-12  112334        58436
10  200 2016-11-10  2016-11-13  110781        58436
11  200 2016-11-10  2016-11-14   33503        58436
12  200 2016-11-10  2016-11-15   26440        58436
13  200 2016-11-10  2016-11-16   23296        58436
14  200 2016-11-10  2016-11-17   20361        58436
15  200 2016-11-10  2016-11-18    1159        58436
16  200 2016-11-11  1970-01-01     280        31215
17  200 2016-11-11  2016-11-04       2        31215
18  200 2016-11-11  2016-11-09     200        31215
19  200 2016-11-11  2016-11-11  173547        31215
20  200 2016-11-11  2016-11-12  130775        31215
21  200 2016-11-11  2016-11-13   53166        31215
22  200 2016-11-11  2016-11-14   19047        31215
23  200 2016-11-11  2016-11-15   16052        31215
24  200 2016-11-11  2016-11-16   23536        31215
25  200 2016-11-11  2016-11-17   23859        31215
26  200 2016-11-11  2016-11-18    2288        31215
27  200 2016-11-12  1970-01-01      35        34220
28  200 2016-11-12  2016-11-09      96        34220
29  200 2016-11-12  2016-11-12  171840        34220
..  ...        ...         ...     ...          ...
69  200 2016-11-19  1970-01-01      18        16825
70  200 2016-11-20  2016-11-10      19        15786
71  200 2016-11-21  1970-01-01      69        10356
72  200 2016-11-21  2016-11-07       7        10356
73  200 2016-11-22  1970-01-01     142        10779
74  200 2016-11-23  1970-01-01      68         9875
75  200 2016-11-23  2016-11-07       6         9875
76  200 2016-11-24  1970-01-01       6         9178
77  200 2016-11-25  2016-11-07       5         9422
78  200 2016-11-26  1970-01-01     204        13979
79  200 2016-11-27  1970-01-01      68        12941
80  200 2016-11-28  1970-01-01       6         8071
81  200 2016-11-29  1970-01-01     104         7331
82  200 2016-12-01  1970-01-01      30         9894
83  200 2016-12-01  2016-11-07       1         9894
84  200 2016-12-01  2016-11-09       3         9894
85  200 2016-12-02  1970-01-01      19        11396
86  200 2016-12-08  1970-01-01      68         6470
87  200 2016-12-15  2016-11-02      98         4701
88  200 2016-12-28  2016-11-02       6         3771
89  200 2016-12-28  2016-11-04       6         3771
90  200 2016-12-28  2016-11-05      12         3771
91  200 2016-12-28  2016-11-09       7         3771
92  200 2017-01-05  2016-11-09       3         4316
93  200 2017-01-19  2016-11-02       2         3405
94  200 2017-01-19  2016-11-04       2         3405
95  200 2017-02-27  2016-11-10      18         1609
96  200 2017-03-31  2016-11-02       2         1571
97  200 2017-03-31  2016-11-04       2         1571
98  200 2017-04-07  2016-11-05       2         1079

[99 rows x 5 columns]

In [41]:
    summaryInfo = {}
    for x in cc.iterrows():
        info = x[1]
        if info.gid not in summaryInfo:
            summaryInfo.setdefault(info.gid,{})
            summaryInfo[info.gid].setdefault(info.date,{})
            summaryInfo[info.gid][info.date].setdefault(info.PayTime,{})
            summaryInfo[info.gid][info.date][info.PayTime].setdefault("Money",info.Money)
            summaryInfo[info.gid][info.date][info.PayTime].setdefault("peopleCount",info.peopleCount)
            

        elif info.date not in summaryInfo[info.gid]:
            summaryInfo[info.gid].setdefault(info.date,{})
            summaryInfo[info.gid][info.date].setdefault(info.PayTime,{})
            summaryInfo[info.gid][info.date][info.PayTime].setdefault("Money",info.Money)
            summaryInfo[info.gid][info.date][info.PayTime].setdefault("peopleCount",info.peopleCount)

        elif info.PayTime not in summaryInfo[info.gid][info.date]:
            summaryInfo[info.gid][info.date].setdefault(info.PayTime,{})
            summaryInfo[info.gid][info.date][info.PayTime].setdefault("Money",info.Money)
            summaryInfo[info.gid][info.date][info.PayTime].setdefault("peopleCount",info.peopleCount)
            
        else:
            print "ERROR"

In [63]:
    
    summaryInfoList = []
    for x in cc.iterrows():
        summaryInfo22 = {}
        info = x[1]
        summaryInfo22.setdefault("Gid",info.gid)
        summaryInfo22.setdefault("Date",info.date)
        summaryInfo22.setdefault("PayTime",info.PayTime)
        summaryInfo22.setdefault("PeopleCount",info.peopleCount)
        summaryInfo22.setdefault("Money",info.Money)
        summaryInfoList.append(summaryInfo22)

In [53]:
    summaryInfoList

{'Money': 172,
 'PayTime': u'1970-01-01',
 'date': Timestamp('2016-11-10 00:00:00'),
 'gid': 200,
 'peopleCount': 58436}

In [73]:
    from pandas.core.frame import DataFrame
    oo = pd.DataFrame(summaryInfoList, columns = ['Gid','Date','PeopleCount','PayTime','Money'])

In [74]:
    oo

    Gid       Date  PeopleCount     PayTime   Money
0   200 2016-11-10        58436  1970-01-01     172
1   200 2016-11-10        58436  2016-11-02     865
2   200 2016-11-10        58436  2016-11-04      49
3   200 2016-11-10        58436  2016-11-05      18
4   200 2016-11-10        58436  2016-11-07      31
5   200 2016-11-10        58436  2016-11-08       8
6   200 2016-11-10        58436  2016-11-09       4
7   200 2016-11-10        58436  2016-11-10  416759
8   200 2016-11-10        58436  2016-11-11  181275
9   200 2016-11-10        58436  2016-11-12  112334
10  200 2016-11-10        58436  2016-11-13  110781
11  200 2016-11-10        58436  2016-11-14   33503
12  200 2016-11-10        58436  2016-11-15   26440
13  200 2016-11-10        58436  2016-11-16   23296
14  200 2016-11-10        58436  2016-11-17   20361
15  200 2016-11-10        58436  2016-11-18    1159
16  200 2016-11-11        31215  1970-01-01     280
17  200 2016-11-11        31215  2016-11-04       2
18  200 2016-11-11        31215  2016-11-09     200
19  200 2016-11-11        31215  2016-11-11  173547
20  200 2016-11-11        31215  2016-11-12  130775
21  200 2016-11-11        31215  2016-11-13   53166
22  200 2016-11-11        31215  2016-11-14   19047
23  200 2016-11-11        31215  2016-11-15   16052
24  200 2016-11-11        31215  2016-11-16   23536
25  200 2016-11-11        31215  2016-11-17   23859
26  200 2016-11-11        31215  2016-11-18    2288
27  200 2016-11-12        34220  1970-01-01      35
28  200 2016-11-12        34220  2016-11-09      96
29  200 2016-11-12        34220  2016-11-12  171840
..  ...        ...          ...         ...     ...
69  200 2016-11-19        16825  1970-01-01      18
70  200 2016-11-20        15786  2016-11-10      19
71  200 2016-11-21        10356  1970-01-01      69
72  200 2016-11-21        10356  2016-11-07       7
73  200 2016-11-22        10779  1970-01-01     142
74  200 2016-11-23         9875  1970-01-01      68
75  200 2016-11-23         9875  2016-11-07       6
76  200 2016-11-24         9178  1970-01-01       6
77  200 2016-11-25         9422  2016-11-07       5
78  200 2016-11-26        13979  1970-01-01     204
79  200 2016-11-27        12941  1970-01-01      68
80  200 2016-11-28         8071  1970-01-01       6
81  200 2016-11-29         7331  1970-01-01     104
82  200 2016-12-01         9894  1970-01-01      30
83  200 2016-12-01         9894  2016-11-07       1
84  200 2016-12-01         9894  2016-11-09       3
85  200 2016-12-02        11396  1970-01-01      19
86  200 2016-12-08         6470  1970-01-01      68
87  200 2016-12-15         4701  2016-11-02      98
88  200 2016-12-28         3771  2016-11-02       6
89  200 2016-12-28         3771  2016-11-04       6
90  200 2016-12-28         3771  2016-11-05      12
91  200 2016-12-28         3771  2016-11-09       7
92  200 2017-01-05         4316  2016-11-09       3
93  200 2017-01-19         3405  2016-11-02       2
94  200 2017-01-19         3405  2016-11-04       2
95  200 2017-02-27         1609  2016-11-10      18
96  200 2017-03-31         1571  2016-11-02       2
97  200 2017-03-31         1571  2016-11-04       2
98  200 2017-04-07         1079  2016-11-05       2

[99 rows x 5 columns]

In [78]:
    data2 = oo.reset_index()
    data3 = data2.set_index(["Gid","Date","PeopleCount", "PayTime"])   # index is the new column created by reset_index
    running_sum = data3.groupby(level=[0,1,2,3]).sum().groupby(level=[0,1]).cumsum()  
    del running_sum['index']

In [79]:
    running_sum

                                        Money
Gid Date       PeopleCount PayTime
200 2016-11-10 58436       1970-01-01     172
                           2016-11-02    1037
                           2016-11-04    1086
                           2016-11-05    1104
                           2016-11-07    1135
                           2016-11-08    1143
                           2016-11-09    1147
                           2016-11-10  417906
                           2016-11-11  599181
                           2016-11-12  711515
                           2016-11-13  822296
                           2016-11-14  855799
                           2016-11-15  882239
                           2016-11-16  905535
                           2016-11-17  925896
                           2016-11-18  927055
    2016-11-11 31215       1970-01-01     280
                           2016-11-04     282
                           2016-11-09     482
                           2016-11-11  174029
                           2016-11-12  304804
                           2016-11-13  357970
                           2016-11-14  377017
                           2016-11-15  393069
                           2016-11-16  416605
                           2016-11-17  440464
                           2016-11-18  442752
    2016-11-12 34220       1970-01-01      35
                           2016-11-09     131
                           2016-11-12  171971
...                                       ...
    2016-11-19 16825       1970-01-01      18
    2016-11-20 15786       2016-11-10      19
    2016-11-21 10356       1970-01-01      69
                           2016-11-07      76
    2016-11-22 10779       1970-01-01     142
    2016-11-23 9875        1970-01-01      68
                           2016-11-07      74
    2016-11-24 9178        1970-01-01       6
    2016-11-25 9422        2016-11-07       5
    2016-11-26 13979       1970-01-01     204
    2016-11-27 12941       1970-01-01      68
    2016-11-28 8071        1970-01-01       6
    2016-11-29 7331        1970-01-01     104
    2016-12-01 9894        1970-01-01      30
                           2016-11-07      31
                           2016-11-09      34
    2016-12-02 11396       1970-01-01      19
    2016-12-08 6470        1970-01-01      68
    2016-12-15 4701        2016-11-02      98
    2016-12-28 3771        2016-11-02       6
                           2016-11-04      12
                           2016-11-05      24
                           2016-11-09      31
    2017-01-05 4316        2016-11-09       3
    2017-01-19 3405        2016-11-02       2
                           2016-11-04       4
    2017-02-27 1609        2016-11-10      18
    2017-03-31 1571        2016-11-02       2
                           2016-11-04       4
    2017-04-07 1079        2016-11-05       2

[99 rows x 1 columns]

In [6]:
pay

,Money,PayTime,acid,gid,uid
0,1,2016-11-11,200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21,200,2f4e9362-1d87-48df-ba35-011f278a8a21
1,6,2016-11-15,200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55,200,99ca640f-1c2f-4e6a-b57c-2fd107139d55
2,6,2016-11-15,200:1009:1337f849-a408-4a05-bcde-d941315d0ba1,200,1337f849-a408-4a05-bcde-d941315d0ba1
3,25,2016-11-11,200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd,200,4ef0daaf-a6cd-433f-8937-a520ebd07acd
4,328,2016-11-12,200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676,200,a60aa1e3-8042-4764-b510-46fdd0d73676
5,30,2016-11-11,200:1001:58a95093-15d6-4261-9151-b6dd03029f3e,200,58a95093-15d6-4261-9151-b6dd03029f3e
6,98,2016-11-13,200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87,200,14ebc642-bbfd-4a0a-b56a-9de573c23c87
7,6,2016-11-13,200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220,200,92e31e79-2cdc-43c9-9fad-ce7ec6fae220
8,6,2016-11-15,200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953,200,772fc1c4-a142-4bfc-afcf-750b64cef953
9,6,2016-11-15,200:1004:82143338-3495-46b0-b00d-fe84a7c94225,200,82143338-3495-46b0-b00d-fe84a7c94225
10,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,200,e5699789-ce13-47ec-aba5-1a4b2aedfcff
11,1,2016-11-12,200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e,200,f78a801b-4be8-4a19-a8cd-d45072c54c3e
12,6,2016-11-12,200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9,200,6189a20a-343f-4ec0-a57c-e471c6afe5f9
13,98,2016-11-14,200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b,200,11b12fa4-41f8-4501-ad5a-9a4c863e414b
14,68,2016-11-18,200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,200,dfd48ca8-c206-43c7-bb3e-a65c5512ebc2
15,30,2016-11-13,200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,200,2bbf8a15-67fb-4dd7-beb8-519bf3ffda16
16,6,2016-11-17,200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,200,e8d06097-b6bc-4c07-b605-a16c5e8ee6c9
17,68,2016-11-10,200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268,200,d7479b16-a64b-4aac-83ab-bd9128d35268
18,30,2016-11-12,200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be,200,f937bef6-41aa-48cc-8638-c6866e6ad8be
19,6,2016-11-11,200:1001:3039ef63-1524-46cf-ba49-9188aa081002,200,3039ef63-1524-46cf-ba49-9188aa081002
20,648,2016-11-10,200:1004:87614525-f38c-43ce-a153-60ef0e2f1578,200,87614525-f38c-43ce-a153-60ef0e2f1578
21,25,2016-11-11,200:1001:0d39521a-4a45-480c-8772-7c24225c6c48,200,0d39521a-4a45-480c-8772-7c24225c6c48
22,6,2016-11-11,200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b,200,20cd29e1-1d00-4429-b85e-44ab5cdafa3b
23,6,2016-11-10,200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b,200,ba6e64ec-97bd-45e7-ab04-a3023688971b
24,1,2016-11-12,200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97,200,d9dcca4e-3aa0-41a0-a586-6ac071976b97
25,6,2016-11-10,200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027,200,b1fcb7b5-a7ae-495f-b53b-7d36f557f027
26,6,2016-11-13,200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3,200,f23121c7-4324-4a75-87f8-3a89ae8eb4a3
27,6,2016-11-12,200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3,200,524dacd8-fcd1-41f4-9111-b6372a1635e3
28,6,2016-11-10,200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153,200,0d464ea9-3a72-4e24-8637-e409a7b67153
29,25,2016-11-14,200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee,200,413c5fbc-922b-428f-8bb7-b23085f3a3ee
...,...,...,...,...,...
57660,6,2016-11-18,200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98,200,c81b59f3-4fcd-48fc-8feb-708e4703ae98
57661,1,2016-11-13,200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7,200,844a0b58-2c0e-460a-a777-16f4a1d0f1b7
57662,30,2016-11-13,200:1009:806567a1-8565-423f-8e04-42cf1b4dade6,200,806567a1-8565-423f-8e04-42cf1b4dade6
57663,68,2016-11-16,200:1013:85db0143-369d-4351-8698-4842eb50534f,200,85db0143-369d-4351-8698-4842eb50534f
57664,6,1970-01-01,200:1010:aafe8ff2-029d-4a77-b395-af0de514df88,200,aafe8ff2-029d-4a77-b395-af0de514df88
57665,30,2016-11-14,200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,200,9bb36b5a-97cc-4ad7-8a25-1e2272281a5b
57666,6,2016-11-10,200:1003:32c155c7-050a-440b-968a-a5000e6add3c,200,32c155c7-050a-440b-968a-a5000e6add3c
57667,1,2016-11-10,200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b,200,ee8b742e-47e7-4da7-acbe-3e981de4322b
57668,25,2016-11-13,200:1011:1369c61f-b375-4bf8-bb11-b9220301362e,200,1369c61f-b375-4bf8-bb11-b9220301362e
57669,6,2016-11-11,200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,200,a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f
57670,68,2016-11-14,200:1011:714f9a06-decc-402b-8e49-3205bf97ba31,200,714f9a06-decc-402b-8e49-3205bf97ba31
57671,25,2016-11-16,200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea,200,64c0cc4b-7dd6-4de6-8075-27954b629dea
57672,68,2016-11-12,200:1002:95940643-2054-48db-b352-25060ddf191e,200,95940643-2054-48db-b352-25060ddf191e
57673,6,2016-11-13,200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702,200,880fd636-cc7e-4ce2-8840-73dcca43a702
57674,30,2016-11-12,200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d,200,6a4f7847-50bd-43b9-bfa6-c8445413503d
57675,6,2016-11-13,200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a,200,8a9ea03e-2045-4f2d-a987-548c8299e57a
57676,6,2016-11-15,200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40,200,ab861363-a5b5-40f8-8b51-559c6797eb40
57677,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,200,e5699789-ce13-47ec-aba5-1a4b2aedfcff
57678,30,2016-11-15,200:1004:36f79246-bb89-483a-be3b-630c6f4e1032,200,36f79246-bb89-483a-be3b-630c6f4e1032
57679,68,2016-11-13,200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,200,7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850
57680,6,2016-11-14,200:1004:17926a73-59eb-4467-89f1-9e9978a019dc,200,17926a73-59eb-4467-89f1-9e9978a019dc
57681,30,2016-11-13,200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e,200,7541a26e-10d7-4bbc-9b5f-a480e766c05e
57682,30,2016-11-17,200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea,200,205ec6d1-d46e-42ea-a9f0-908017ef57ea
57683,1,2016-11-12,200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724,200,93c29e25-8623-4004-bd50-cf6cbfe81724
57684,1,2016-11-11,200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598,200,6f69a8ba-afea-464e-b72a-1c9ee9057598
57685,6,2016-11-15,200:1006:0875ee8b-2319-4458-b85a-031760c5535f,200,0875ee8b-2319-4458-b85a-031760c5535f
57686,6,2016-11-17,200:1011:312fda94-6cfc-4299-9b63-6964df5b224a,200,312fda94-6cfc-4299-9b63-6964df5b224a
57687,30,2016-11-17,200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333,200,aafffa5b-ba19-4c40-b85a-64e0f3979333
57688,1,2016-11-10,200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,200,9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7
57689,1,2016-11-13,200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,200,aa81f47d-99bc-4c68-a31e-ff9c1e21f1df

In [7]:
uid_temp

                                          uid       date  gid
0        ea189bea-6ecd-43a9-b8a9-45d262359e08 2017-03-29  202
1        91ab331e-ba04-4ec9-8d49-dc354e78f08e 2016-12-19  202
2        22bd437d-4c02-4f0f-b29e-a19c944d87f5 2016-12-26  202
3        ffe676fd-a3e1-460f-828c-794924c86373 2016-12-08  200
4        af43f40d-1b55-4da7-bc37-0b3878c313b2 2017-03-07  202
5        5dc27c9d-c973-443c-89a8-89a1d522b3f6 2016-11-22  202
6        2be36a08-8c59-4051-ae45-a1cbea2a2056 2016-12-19  202
7        d5c8efc3-64ce-4fc7-bcd4-666e5c06a048 2017-02-01  202
8        47a9af46-fc2f-4d16-bc59-637f1a8d98b0 2016-11-14  200
9        a9b8c704-f089-4926-b73e-d7962061a09b 2016-12-03  202
10       050ed2fd-8db9-4604-9a43-3e306e6792c3 2016-11-28  202
11       f062101a-5644-4427-ac58-8954fd951c33 2016-11-11  201
12       a186468f-6eaa-45cd-932f-41db9456a913 2017-03-14  202
13       21d9f577-70cc-46a7-bb7a-8113b1ab9505 2017-02-27  200
14       62e304a5-32e2-4c77-9047-c59958ba7727 2017-02-01  202
15       b11a1955-75f7-4bc6-87e7-ed4912942bae 2017-02-08  202
16       712a8893-ee9f-4951-bbb6-3d91c61470e0 2016-11-19  202
17       63bf7c41-fd50-43bb-a4a1-4bd525140c67 2017-01-02  202
18       0daedbbb-f029-48a9-a126-66ede78f2c8c 2017-02-11  202
19       c90384d3-450d-4ad7-ae6c-c673d065100e 2017-02-16  202
20       4af960f8-9259-4319-b92c-63e924c317fa 2016-11-15  200
21       8cacb449-695d-4b9b-af83-b9346aad23aa 2017-02-25  202
22       cf2cfa1b-2beb-4e17-9f74-e12f073d480b 2017-01-08  200
23       f1b47cbd-dabf-40aa-9601-9fe8831753c8 2017-03-27  202
24       82888097-93bf-443d-b267-dc6562d35743 2017-01-06  202
25       ad8ba922-7433-44ec-8afa-208fa37b9bb8 2017-01-15  201
26       56a3fab2-078c-46ea-9596-1cd16c7819f2 2017-02-11  202
27       08d5602d-d2f0-4182-a881-598ce5fa8875 2016-12-09  202
28       14285670-aea7-456b-be1e-f95962a8a5d9 2016-11-10  200
29       88c1a2f5-a116-4148-9a31-4f5462f9bc25 2016-12-10  201
...                                       ...        ...  ...
2834421  6940ecc3-3816-4cc4-a8b1-2551d02c8ff4 2017-02-25  202
2834422  bbc02776-aa53-4d19-9f32-7ddd067c7fca 2016-11-14  200
2834423  d1afae19-e1ce-4f42-b04f-6fdebfa3e97c 2017-02-10  202
2834424  bbc80344-7f01-4da6-a0ba-b4ed97bbed75 2016-11-10  202
2834425  8a77ed78-d27d-4ab4-8d8e-d39e21251104 2017-02-25  202
2834426  3bac0acf-6d02-4ce2-bacc-76e3feaec5b3 2016-11-18  200
2834427  45c8cebc-cc6d-4197-91e2-3dafadd1b4f8 2017-04-08  202
2834428  03af31db-8a45-4d38-9144-5236d7060843 2016-11-21  200
2834429  d3440179-7487-4c13-8a7b-bfa3ba2c6db8 2016-11-10  200
2834430  6cb0c113-2896-4ff9-a341-36a8dd6089f6 2017-02-12  202
2834431  9c7c5a22-7b52-4de0-9232-0e3577d49673 2016-12-22  202
2834432  3046f5a2-2b58-4fab-a051-4931c6b7626b 2017-03-05  202
2834433  615966c3-68a9-40f2-b345-ab3cee0d2216 2016-12-02  202
2834434  60366e05-7a61-48d5-9a74-8a5b50718950 2016-11-12  200
2834435  2ee90cc2-d6f5-4419-8553-adf8f0ebf141 2017-03-24  200
2834436  02ed360b-5ab0-47bb-ab1d-a880a0f168f5 2016-11-20  200
2834437  6dc20d9a-cc6f-41b4-bdf3-1df183abe4e6 2017-02-03  202
2834438  78f15bbe-19f6-4c55-bcd4-70317d319fd2 2017-03-04  202
2834439  2a303cd0-41ce-485f-8ae2-0cf43e2acb66 2016-12-31  202
2834440  a2c4ca34-8dc6-47fe-ac09-fc453fff24f7 2016-11-14  201
2834441  f60c7b15-5f8b-4aa4-b2fa-7d74ee97cc2e 2017-02-07  202
2834442  341e9d75-dc0a-4e1a-8bac-da7c634c2c7e 2016-12-21  200
2834443  73ebd3f3-f532-4235-b278-2f5b4bb80a18 2016-12-29  202
2834444  fde32a43-dda2-4cac-bbaa-249295fc83ec 2016-11-26  202
2834445  e1948515-b73c-4e07-a278-0e82e48e4c80 2017-02-17  202
2834446  e8d53b6f-59cf-4844-a474-45a6c6a42801 2016-11-10  200
2834447  4e02c164-04a1-4239-960f-fa5fc5d76f64 2017-02-10  200
2834448  c4f0b3d5-049d-414a-b63a-97c7391f1023 2016-11-26  202
2834449  e06a1aa3-4e9b-4d96-b96f-61238338fff3 2016-12-05  202
2834450  264b6750-647e-4a06-a05f-8405d1a23ad1 2017-01-29  202

[2834451 rows x 3 columns]

In [8]:
creatGroup

          date  gid  peopleCount
0   2016-11-10  200        58436
1   2016-11-10  201         3079
2   2016-11-10  202        23452
3   2016-11-11  200        31215
4   2016-11-11  201        21607
5   2016-11-11  202        15406
6   2016-11-12  200        34220
7   2016-11-12  201        23025
8   2016-11-12  202        14917
9   2016-11-13  200        25033
10  2016-11-13  201        16771
11  2016-11-13  202        12139
12  2016-11-14  200        18442
13  2016-11-14  201        10191
14  2016-11-14  202         9876
15  2016-11-15  200        18130
16  2016-11-15  201         8327
17  2016-11-15  202         7800
18  2016-11-16  200        14023
19  2016-11-16  201         7671
20  2016-11-16  202         6753
21  2016-11-17  200        12266
22  2016-11-17  201         6863
23  2016-11-17  202         8391
24  2016-11-18  200        12021
25  2016-11-18  201         3480
26  2016-11-18  202        14028
27  2016-11-19  200        16825
28  2016-11-19  201         2811
29  2016-11-19  202        16704
..         ...  ...          ...
426 2017-04-01  200         1879
427 2017-04-01  201          561
428 2017-04-01  202         4179
429 2017-04-02  200         3671
430 2017-04-02  201          684
431 2017-04-02  202         5295
432 2017-04-03  200         2381
433 2017-04-03  201          660
434 2017-04-03  202         4773
435 2017-04-04  200         2377
436 2017-04-04  201          527
437 2017-04-04  202         4718
438 2017-04-05  200         1099
439 2017-04-05  201          352
440 2017-04-05  202         3163
441 2017-04-06  200         1055
442 2017-04-06  201          328
443 2017-04-06  202         2618
444 2017-04-07  200         1079
445 2017-04-07  201          334
446 2017-04-07  202         3673
447 2017-04-08  200         2888
448 2017-04-08  201          434
449 2017-04-08  202         5102
450 2017-04-09  200         1624
451 2017-04-09  201          383
452 2017-04-09  202         5066
453 2017-04-10  200          119
454 2017-04-10  201           43
455 2017-04-10  202          363

[456 rows x 3 columns]

In [9]:
payMerge

,Money,PayTime,acid,gid,uid,date,gid_r
0,1,2016-11-11,200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21,200,2f4e9362-1d87-48df-ba35-011f278a8a21,2016-11-11,200.0
1,6,2016-11-15,200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55,200,99ca640f-1c2f-4e6a-b57c-2fd107139d55,2016-11-15,200.0
2,6,2016-11-15,200:1009:1337f849-a408-4a05-bcde-d941315d0ba1,200,1337f849-a408-4a05-bcde-d941315d0ba1,2016-11-12,200.0
3,25,2016-11-11,200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd,200,4ef0daaf-a6cd-433f-8937-a520ebd07acd,2016-11-10,200.0
4,328,2016-11-12,200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676,200,a60aa1e3-8042-4764-b510-46fdd0d73676,2016-11-11,200.0
5,30,2016-11-11,200:1001:58a95093-15d6-4261-9151-b6dd03029f3e,200,58a95093-15d6-4261-9151-b6dd03029f3e,2016-11-10,200.0
6,98,2016-11-13,200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87,200,14ebc642-bbfd-4a0a-b56a-9de573c23c87,2016-11-13,200.0
7,6,2016-11-13,200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220,200,92e31e79-2cdc-43c9-9fad-ce7ec6fae220,2016-11-10,200.0
8,6,2016-11-15,200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953,200,772fc1c4-a142-4bfc-afcf-750b64cef953,2016-11-14,200.0
9,6,2016-11-15,200:1004:82143338-3495-46b0-b00d-fe84a7c94225,200,82143338-3495-46b0-b00d-fe84a7c94225,2016-11-11,200.0
10,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,200,e5699789-ce13-47ec-aba5-1a4b2aedfcff,2016-11-10,200.0
11,1,2016-11-12,200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e,200,f78a801b-4be8-4a19-a8cd-d45072c54c3e,2016-11-10,200.0
12,6,2016-11-12,200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9,200,6189a20a-343f-4ec0-a57c-e471c6afe5f9,2016-11-10,200.0
13,98,2016-11-14,200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b,200,11b12fa4-41f8-4501-ad5a-9a4c863e414b,2016-11-10,200.0
14,68,2016-11-18,200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,200,dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,2016-11-17,200.0
15,30,2016-11-13,200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,200,2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,2016-11-12,200.0
16,6,2016-11-17,200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,200,e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,2016-11-11,200.0
17,68,2016-11-10,200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268,200,d7479b16-a64b-4aac-83ab-bd9128d35268,2016-11-10,200.0
18,30,2016-11-12,200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be,200,f937bef6-41aa-48cc-8638-c6866e6ad8be,2016-11-12,200.0
19,6,2016-11-11,200:1001:3039ef63-1524-46cf-ba49-9188aa081002,200,3039ef63-1524-46cf-ba49-9188aa081002,2016-11-10,200.0
20,648,2016-11-10,200:1004:87614525-f38c-43ce-a153-60ef0e2f1578,200,87614525-f38c-43ce-a153-60ef0e2f1578,2016-11-10,200.0
21,25,2016-11-11,200:1001:0d39521a-4a45-480c-8772-7c24225c6c48,200,0d39521a-4a45-480c-8772-7c24225c6c48,2016-11-10,200.0
22,6,2016-11-11,200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b,200,20cd29e1-1d00-4429-b85e-44ab5cdafa3b,2016-11-10,200.0
23,6,2016-11-10,200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b,200,ba6e64ec-97bd-45e7-ab04-a3023688971b,2016-11-10,200.0
24,1,2016-11-12,200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97,200,d9dcca4e-3aa0-41a0-a586-6ac071976b97,2016-11-10,200.0
25,6,2016-11-10,200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027,200,b1fcb7b5-a7ae-495f-b53b-7d36f557f027,2016-11-10,200.0
26,6,2016-11-13,200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3,200,f23121c7-4324-4a75-87f8-3a89ae8eb4a3,2016-11-11,200.0
27,6,2016-11-12,200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3,200,524dacd8-fcd1-41f4-9111-b6372a1635e3,2016-11-10,200.0
28,6,2016-11-10,200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153,200,0d464ea9-3a72-4e24-8637-e409a7b67153,2016-11-10,200.0
29,25,2016-11-14,200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee,200,413c5fbc-922b-428f-8bb7-b23085f3a3ee,2016-11-14,200.0
...,...,...,...,...,...,...,...
57660,6,2016-11-18,200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98,200,c81b59f3-4fcd-48fc-8feb-708e4703ae98,2016-11-11,200.0
57661,1,2016-11-13,200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7,200,844a0b58-2c0e-460a-a777-16f4a1d0f1b7,2016-11-10,200.0
57662,30,2016-11-13,200:1009:806567a1-8565-423f-8e04-42cf1b4dade6,200,806567a1-8565-423f-8e04-42cf1b4dade6,2016-11-12,200.0
57663,68,2016-11-16,200:1013:85db0143-369d-4351-8698-4842eb50534f,200,85db0143-369d-4351-8698-4842eb50534f,2016-11-15,200.0
57664,6,1970-01-01,200:1010:aafe8ff2-029d-4a77-b395-af0de514df88,200,aafe8ff2-029d-4a77-b395-af0de514df88,2016-11-10,200.0
57665,30,2016-11-14,200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,200,9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,2016-11-14,200.0
57666,6,2016-11-10,200:1003:32c155c7-050a-440b-968a-a5000e6add3c,200,32c155c7-050a-440b-968a-a5000e6add3c,2016-11-10,200.0
57667,1,2016-11-10,200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b,200,ee8b742e-47e7-4da7-acbe-3e981de4322b,2016-11-10,200.0
57668,25,2016-11-13,200:1011:1369c61f-b375-4bf8-bb11-b9220301362e,200,1369c61f-b375-4bf8-bb11-b9220301362e,2016-11-13,200.0
57669,6,2016-11-11,200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,200,a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,2016-11-10,200.0
57670,68,2016-11-14,200:1011:714f9a06-decc-402b-8e49-3205bf97ba31,200,714f9a06-decc-402b-8e49-3205bf97ba31,2016-11-13,200.0
57671,25,2016-11-16,200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea,200,64c0cc4b-7dd6-4de6-8075-27954b629dea,2016-11-10,200.0
57672,68,2016-11-12,200:1002:95940643-2054-48db-b352-25060ddf191e,200,95940643-2054-48db-b352-25060ddf191e,2016-11-10,200.0
57673,6,2016-11-13,200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702,200,880fd636-cc7e-4ce2-8840-73dcca43a702,2016-11-13,200.0
57674,30,2016-11-12,200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d,200,6a4f7847-50bd-43b9-bfa6-c8445413503d,2016-11-12,200.0
57675,6,2016-11-13,200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a,200,8a9ea03e-2045-4f2d-a987-548c8299e57a,2016-11-12,200.0
57676,6,2016-11-15,200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40,200,ab861363-a5b5-40f8-8b51-559c6797eb40,2016-11-13,200.0
57677,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,200,e5699789-ce13-47ec-aba5-1a4b2aedfcff,2016-11-10,200.0
57678,30,2016-11-15,200:1004:36f79246-bb89-483a-be3b-630c6f4e1032,200,36f79246-bb89-483a-be3b-630c6f4e1032,2016-11-10,200.0
57679,68,2016-11-13,200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,200,7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,2016-11-12,200.0
57680,6,2016-11-14,200:1004:17926a73-59eb-4467-89f1-9e9978a019dc,200,17926a73-59eb-4467-89f1-9e9978a019dc,2016-11-11,200.0
57681,30,2016-11-13,200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e,200,7541a26e-10d7-4bbc-9b5f-a480e766c05e,2016-11-12,200.0
57682,30,2016-11-17,200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea,200,205ec6d1-d46e-42ea-a9f0-908017ef57ea,2016-11-15,200.0
57683,1,2016-11-12,200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724,200,93c29e25-8623-4004-bd50-cf6cbfe81724,2016-11-11,200.0
57684,1,2016-11-11,200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598,200,6f69a8ba-afea-464e-b72a-1c9ee9057598,2016-11-11,200.0
57685,6,2016-11-15,200:1006:0875ee8b-2319-4458-b85a-031760c5535f,200,0875ee8b-2319-4458-b85a-031760c5535f,2016-11-12,200.0
57686,6,2016-11-17,200:1011:312fda94-6cfc-4299-9b63-6964df5b224a,200,312fda94-6cfc-4299-9b63-6964df5b224a,2016-11-13,200.0
57687,30,2016-11-17,200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333,200,aafffa5b-ba19-4c40-b85a-64e0f3979333,2016-11-17,200.0
57688,1,2016-11-10,200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,200,9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,2016-11-10,200.0
57689,1,2016-11-13,200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,200,aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,2016-11-12,200.0

In [12]:
temp_sum

    gid       date     PayTime   Money
0   200 2016-11-10  1970-01-01     172
1   200 2016-11-10  2016-11-02    1037
2   200 2016-11-10  2016-11-04    1086
3   200 2016-11-10  2016-11-05    1104
4   200 2016-11-10  2016-11-07    1135
5   200 2016-11-10  2016-11-08    1143
6   200 2016-11-10  2016-11-09    1147
7   200 2016-11-10  2016-11-10  417906
8   200 2016-11-10  2016-11-11  599181
9   200 2016-11-10  2016-11-12  711515
10  200 2016-11-10  2016-11-13  822296
11  200 2016-11-10  2016-11-14  855799
12  200 2016-11-10  2016-11-15  882239
13  200 2016-11-10  2016-11-16  905535
14  200 2016-11-10  2016-11-17  925896
15  200 2016-11-10  2016-11-18  927055
16  200 2016-11-11  1970-01-01     280
17  200 2016-11-11  2016-11-04     282
18  200 2016-11-11  2016-11-09     482
19  200 2016-11-11  2016-11-11  174029
20  200 2016-11-11  2016-11-12  304804
21  200 2016-11-11  2016-11-13  357970
22  200 2016-11-11  2016-11-14  377017
23  200 2016-11-11  2016-11-15  393069
24  200 2016-11-11  2016-11-16  416605
25  200 2016-11-11  2016-11-17  440464
26  200 2016-11-11  2016-11-18  442752
27  200 2016-11-12  1970-01-01      35
28  200 2016-11-12  2016-11-09     131
29  200 2016-11-12  2016-11-12  171971
..  ...        ...         ...     ...
69  200 2016-11-19  1970-01-01      18
70  200 2016-11-20  2016-11-10      19
71  200 2016-11-21  1970-01-01      69
72  200 2016-11-21  2016-11-07      76
73  200 2016-11-22  1970-01-01     142
74  200 2016-11-23  1970-01-01      68
75  200 2016-11-23  2016-11-07      74
76  200 2016-11-24  1970-01-01       6
77  200 2016-11-25  2016-11-07       5
78  200 2016-11-26  1970-01-01     204
79  200 2016-11-27  1970-01-01      68
80  200 2016-11-28  1970-01-01       6
81  200 2016-11-29  1970-01-01     104
82  200 2016-12-01  1970-01-01      30
83  200 2016-12-01  2016-11-07      31
84  200 2016-12-01  2016-11-09      34
85  200 2016-12-02  1970-01-01      19
86  200 2016-12-08  1970-01-01      68
87  200 2016-12-15  2016-11-02      98
88  200 2016-12-28  2016-11-02       6
89  200 2016-12-28  2016-11-04      12
90  200 2016-12-28  2016-11-05      24
91  200 2016-12-28  2016-11-09      31
92  200 2017-01-05  2016-11-09       3
93  200 2017-01-19  2016-11-02       2
94  200 2017-01-19  2016-11-04       4
95  200 2017-02-27  2016-11-10      18
96  200 2017-03-31  2016-11-02       2
97  200 2017-03-31  2016-11-04       4
98  200 2017-04-07  2016-11-05       2

[99 rows x 4 columns]

In [17]:
finalpayMerge

    gid       date     PayTime   Money  peopleCount    consume
0   200 2016-11-10  1970-01-01     172        58436   0.002943
1   200 2016-11-10  2016-11-02    1037        58436   0.017746
2   200 2016-11-10  2016-11-04    1086        58436   0.018584
3   200 2016-11-10  2016-11-05    1104        58436   0.018892
4   200 2016-11-10  2016-11-07    1135        58436   0.019423
5   200 2016-11-10  2016-11-08    1143        58436   0.019560
6   200 2016-11-10  2016-11-09    1147        58436   0.019628
7   200 2016-11-10  2016-11-10  417906        58436   7.151516
8   200 2016-11-10  2016-11-11  599181        58436  10.253628
9   200 2016-11-10  2016-11-12  711515        58436  12.175970
10  200 2016-11-10  2016-11-13  822296        58436  14.071737
11  200 2016-11-10  2016-11-14  855799        58436  14.645065
12  200 2016-11-10  2016-11-15  882239        58436  15.097525
13  200 2016-11-10  2016-11-16  905535        58436  15.496184
14  200 2016-11-10  2016-11-17  925896        58436  15.844616
15  200 2016-11-10  2016-11-18  927055        58436  15.864450
16  200 2016-11-11  1970-01-01     280        31215   0.008970
17  200 2016-11-11  2016-11-04     282        31215   0.009034
18  200 2016-11-11  2016-11-09     482        31215   0.015441
19  200 2016-11-11  2016-11-11  174029        31215   5.575172
20  200 2016-11-11  2016-11-12  304804        31215   9.764664
21  200 2016-11-11  2016-11-13  357970        31215  11.467884
22  200 2016-11-11  2016-11-14  377017        31215  12.078071
23  200 2016-11-11  2016-11-15  393069        31215  12.592311
24  200 2016-11-11  2016-11-16  416605        31215  13.346308
25  200 2016-11-11  2016-11-17  440464        31215  14.110652
26  200 2016-11-11  2016-11-18  442752        31215  14.183950
27  200 2016-11-12  1970-01-01      35        34220   0.001023
28  200 2016-11-12  2016-11-09     131        34220   0.003828
29  200 2016-11-12  2016-11-12  171971        34220   5.025453
..  ...        ...         ...     ...          ...        ...
69  200 2016-11-19  1970-01-01      18        16825   0.001070
70  200 2016-11-20  2016-11-10      19        15786   0.001204
71  200 2016-11-21  1970-01-01      69        10356   0.006663
72  200 2016-11-21  2016-11-07      76        10356   0.007339
73  200 2016-11-22  1970-01-01     142        10779   0.013174
74  200 2016-11-23  1970-01-01      68         9875   0.006886
75  200 2016-11-23  2016-11-07      74         9875   0.007494
76  200 2016-11-24  1970-01-01       6         9178   0.000654
77  200 2016-11-25  2016-11-07       5         9422   0.000531
78  200 2016-11-26  1970-01-01     204        13979   0.014593
79  200 2016-11-27  1970-01-01      68        12941   0.005255
80  200 2016-11-28  1970-01-01       6         8071   0.000743
81  200 2016-11-29  1970-01-01     104         7331   0.014186
82  200 2016-12-01  1970-01-01      30         9894   0.003032
83  200 2016-12-01  2016-11-07      31         9894   0.003133
84  200 2016-12-01  2016-11-09      34         9894   0.003436
85  200 2016-12-02  1970-01-01      19        11396   0.001667
86  200 2016-12-08  1970-01-01      68         6470   0.010510
87  200 2016-12-15  2016-11-02      98         4701   0.020847
88  200 2016-12-28  2016-11-02       6         3771   0.001591
89  200 2016-12-28  2016-11-04      12         3771   0.003182
90  200 2016-12-28  2016-11-05      24         3771   0.006364
91  200 2016-12-28  2016-11-09      31         3771   0.008221
92  200 2017-01-05  2016-11-09       3         4316   0.000695
93  200 2017-01-19  2016-11-02       2         3405   0.000587
94  200 2017-01-19  2016-11-04       4         3405   0.001175
95  200 2017-02-27  2016-11-10      18         1609   0.011187
96  200 2017-03-31  2016-11-02       2         1571   0.001273
97  200 2017-03-31  2016-11-04       4         1571   0.002546
98  200 2017-04-07  2016-11-05       2         1079   0.001854

[99 rows x 6 columns]

In [43]:
import MySQLdb

database = MySQLdb.connect(host="54.223.192.252", user="test1", passwd="QmPhaQ8hYsxx", db="test")
cursor = database.cursor()
date = cursor.execute("select * from ltv_byGid where creat_time = 2016-11-10 and days = (select max(days) from ltv_byGid where creat_time) ")

ImportError: No module named MySQLdb