In [23]:
# -*- coding:utf-8 -*-
from pyspark import SparkContext, SparkConf
from pyspark.sql import SparkSession
from pyspark.sql import Row
from pyspark.sql.types import *
import boto
from boto import s3
import datetime
import pandas as pd
import StringIO
import pytz
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, create_engine,Float
from sqlalchemy.orm import scoped_session, sessionmaker
import os
import time




now_utc = datetime.datetime.utcnow()
local_tz = pytz.timezone('Asia/Shanghai')
now_utc = pytz.utc.localize(now_utc)
local_time = now_utc.astimezone(local_tz)
current_date = local_time.strftime('%Y%m%d')

islocal = True
localPath = "/Users/tq/bigdatatest/"
# targetpay_path = 'uidcreattime-csv/pay/'
# target_path = 'uidcreattime-csv'
# firstDay = datetime.date(2016, 11, 10)

firstDay = datetime.date(2017, 3, 7)
target_path = '/Users/tq/bigdatatest/'
targetpay_path = 'Users/tq/bigdatatest/pay/' #本地
def getFalesChannel():
    false_channel = [
    "130134201",
    "110134101106.0",
    "13013412700",
    "13013419400",
    "130134164",
    "47",
    "13013415800",
    "1301343257",
    "13013413400",
    "131",
    "142",
    "145",
    "180",
    "188",
    "196",
    "204",
    "210",
    "213",
    "215",
    "216",
    "223",
    "234",
    "250",
    "259",
    "262",
    "263",
    "265",
    "292",
    "296",
    "298",
    "306",
    "309",
    "313",
    "1301341500",
    "1301341232",
    "13013416000",
    "13013411000",
    "1301344600",
    "1301345600",
    "13013412000",
    "1301341272",
    "13013415900",
    "130134137",
    "1301371335",
    "130134126",
    "1301343900",
    "13013415200",
    "13013423200",
    "1301343234",
    "130134312108",
    "1301341300",
    "130134312173",
    "5000",
    "130134159",
    "1301343800",
    "1301345400",
    "1301341",
    "130134144",
    "13013443300",
    "268",
    "350",
    "389"
]
    return false_channel

def getTrueChannel():
    true_channel = [
        "130134000201",
        "110134101106",
        "130134012700",
        "130134019400",
        "130134000164",
        "47",
        "130134015800",
        "130134003257",
        "130134013400",
        "131",
        "142",
        "145",
        "180",
        "188",
        "196",
        "204",
        "210",
        "213",
        "215",
        "216",
        "223",
        "234",
        "250",
        "259",
        "262",
        "263",
        "265",
        "292",
        "296",
        "298",
        "306",
        "309",
        "313",
        "130134001500",
        "130134001232",
        "130134016000",
        "130134011000",
        "130134004600",
        "130134005600",
        "130134012000",
        "130134001272",
        "130134015900",
        "130134000137",
        "130134001335",
        "130134000126",
        "130134003900",
        "130134015200",
        "130134023200",
        "130134003234",
        "130134312108",
        "130134001300",
        "130134312173",
        "5000",
        "130134000159",
        "130134003800",
        "130134005400",
        "130134000001",
        "130134000144",
        "130134043300",
        "268",
        "350",
        "389"
    ]
    return true_channel

def getDBDriver(tableName):
    return spark.read.format("jdbc").option("url", url).option("driver", "com.mysql.jdbc.Driver").option(
            "dbtable", tableName).option("user", properties['user']).option("password", properties['password']).load()


def get_s3_list(daterange,prefixpath):
    prefix = prefixpath
    total_size = 0
    REGION = "cn-north-1"
    conn = s3.connect_to_region(REGION)
    bucket = conn.lookup('prodlog')
    ret = []
    if bucket:
        for k in bucket.list(prefix=prefix):
            if k.size <= 0:
                continue
            logsp = k.name.split('.')
            a = logsp[-4:-1]
            a.reverse()
            dt = ''.join(a)
            if dt == daterange:
                total_size += k.size
                ret.append('s3://prodlog/' + k.name)
                print('s3://prodlog/' + k.name, ''.join(a))
    print('total:%d' % (total_size / 1024.0 / 1024.0 / 1024.0))
    return ret


def get_local_list(daterange):
        return "/Users/tq/bigdatatest/%s.log"%daterange

def get_file_list(daterange,prefixpath):
    if islocal:

        return get_local_list(daterange)
    else:
        return get_s3_list(daterange,prefixpath)



def get_s3_tempdata(dataName):
    prefix = "uidcreattime-csv/"
    total_size = 0
    REGION = "cn-north-1"
    conn = s3.connect_to_region(REGION)
    bucket = conn.lookup('prodlog')
    ret = []
    if bucket:
        for k in bucket.list(prefix=prefix):
            if k.size <= 0:
                continue
            if dataName == "payLog":
                logsp = k.name.split('/')
                a = logsp[len(logsp) - 1]
                if dataName in a:
                    total_size += k.size
                    ret.append('s3://prodlog/' + k.name)
                    print('test :s3://prodlog/' + k.name, ''.join(a))
            else:
                logsp = k.name.split('/')
                a = logsp[len(logsp)-1]
                csvName = a.split('.')[0]
                if csvName == dataName:
                    total_size += k.size
                    ret.append('s3://prodlog/' + k.name)
                    print('test :s3://prodlog/' + k.name, ''.join(a))
    print('total:%d' % (total_size / 1024.0 / 1024.0 / 1024.0))
    return ret

def getTempDataList(dataName):
    if islocal:
        return search(localPath,dataName)
    else:
        return get_s3_tempdata(dataName)

def search(path, word):
    name = []
    if word == "payLog":
        for filename in os.listdir("/Users/tq/bigdatatest/pay"):
            fp = os.path.join("/Users/tq/bigdatatest/pay", filename)
            if word in filename:
                name.append(fp)
    else:
        for filename in os.listdir(path):
            fp = os.path.join(path, filename)
            if os.path.isfile(fp) and word in filename:
                name.append(fp)
    print name
    return name

def min_time(x, y):
    if int(x.lt) > int(y.lt):
        return y
    else:
        return x

def upload_to_s3(pandasdf, region, bucket_name, s3_filepath):
    for column in pandasdf.columns:
        for idx in pandasdf[column].index:
            x = pandasdf.get_value(idx, column)
            try:
                x = unicode(x.encode('utf-8', 'ignore'), errors='ignore') if type(x) == unicode else unicode(str(x),errors='ignore')
                pandasdf.set_value(idx, column, x)
            except Exception:
                print
                'encoding error: {0} {1}'.format(idx, column)
                pandasdf.set_value(idx, column, '')
                continue
    json_buffer = StringIO.StringIO()
    pandasdf.to_json(json_buffer,orient='records')
    conn = boto.s3.connect_to_region(region)
    bucket = conn.get_bucket(bucket_name)
    full_key_name = s3_filepath
    k = bucket.new_key(full_key_name)
    k.set_contents_from_string(json_buffer.getvalue())
    return None

def upload_to_local(pandasdf, s3_filepath):
    for column in pandasdf.columns:
        for idx in pandasdf[column].index:
            x = pandasdf.get_value(idx, column)
            try:
                x = unicode(x.encode('utf-8', 'ignore'), errors='ignore') if type(x) == unicode else unicode(str(x),errors='ignore')
                pandasdf.set_value(idx, column, x)
            except Exception:
                print
                'encoding error: {0} {1}'.format(idx, column)
                pandasdf.set_value(idx, column, '')
                continue
    pandasdf.to_json(s3_filepath,orient='records')
    return None


def upload(pandasdf, region, bucket_name, s3_filepath):
    if islocal:
        upload_to_local(pandasdf,s3_filepath)
    else:
        upload_to_s3(pandasdf, region, bucket_name, s3_filepath)

properties = {
    "user": "test1",
    "password": "QmPhaQ8hYsxx"
}
uidTableName = "uid_creatTime"
acidTableName = "account_creatTime"
payTableName = "account_payTime"
url = "jdbc:mysql://54.223.192.252:3306/test"







Base = declarative_base()
dbname='mysql+mysqlconnector://test1:QmPhaQ8hYsxx@54.223.192.252:3306/test'
engine = create_engine(dbname, echo=False)
DBSession = scoped_session(sessionmaker(bind=engine))


class LTVByGid(Base):
    __tablename__ = "ltv_byGid"
    id = Column(Integer, primary_key=True)
    gid = Column(String(255))
    creat_time = Column(String(255))
    people_count = Column(String(255))
    days = Column(String(255))
    consume = Column(Float, nullable=True)

class LTVBySid(Base):
    __tablename__ = "ltv_bySid"
    id = Column(Integer, primary_key=True)
    sid = Column(String(255))
    creat_time = Column(String(255))
    people_count = Column(String(255))
    days = Column(String(255))
    consume = Column(Float, nullable=True)
class LTVByCh(Base):
    __tablename__ = "ltv_byCh"
    id = Column(Integer, primary_key=True)
    ch = Column(String(255))
    creat_time = Column(String(255))
    people_count = Column(String(255))
    days = Column(String(255))
    consume = Column(Float, nullable=True)

def ltv_byGid_sqlalchemy_orm(df):
    # init_sqlalchemy()
    session = DBSession()
    x = []
    for dfdate in df.values:
        customer = LTVByGid()
        customer.gid = str(dfdate[0])
        customer.creat_time = str(dfdate[3])
        customer.people_count = str(dfdate[2])
        customer.days = str(dfdate[4])
        if dfdate[1] is None:
            customer.consume = float(0)
        else:
            customer.consume = float(dfdate[1]) / float(dfdate[2]) / 100
        x.append(customer)
    session.add_all(x)
    session.commit()

def ltv_bySid_sqlalchemy_orm(df):
    # init_sqlalchemy()
    session = DBSession()
    x = []
    for dfdate in df.values:
        customer = LTVBySid()
        customer.sid = str(dfdate[0])
        customer.creat_time = str(dfdate[3])
        customer.people_count = str(dfdate[2])
        customer.days = str(dfdate[4])
        if dfdate[1] is None:
            customer.consume = float(0)
        else:
            customer.consume = float(dfdate[1]) / float(dfdate[2]) / 100
        x.append(customer)
    session.add_all(x)
    session.commit()

def ltv_byCh_sqlalchemy_orm(df):
    # init_sqlalchemy()
    session = DBSession()
    x = []
    for dfdate in df.values:
        customer = LTVByCh()
        customer.ch = str(dfdate[0])
        customer.creat_time = str(dfdate[3])
        customer.people_count = str(dfdate[2])
        customer.days = str(dfdate[4])
        if dfdate[1] is None:
            customer.consume = float(0)
        else:
            customer.consume = float(dfdate[1]) / float(dfdate[2]) / 100
        x.append(customer)
    session.add_all(x)
    session.commit()

if __name__ == '__main__':
    begin = datetime.date(2017, 2, 1)
    end = datetime.date(2017, 6, 21)

    print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "creat spark session"
    spark = SparkSession \
        .builder.enableHiveSupport() \
        .appName("Python Spark SQL basic example") \
        .config("spark.some.config.option", "some-value") \
        .getOrCreate()
    for i in range((end - begin).days + 1):
        xx = str(begin + datetime.timedelta(days=i))
        pp = xx.split('-')
        day = "".join(pp)
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))),"start:",day

        df = spark.read.json(get_file_list(day,"logics3/"))
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish read original data"
        df.createOrReplaceTempView('RawTable')
        preparetable = 'RawTable'

        spark.sql(u'''
        SELECT
            *
        FROM %s
        WHERE accountid is not null
        AND type_name!="CorpLevelChg"
        ''' % preparetable).createOrReplaceTempView('jsonTable')
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish creat today jsonTable"
        # 获取当日log里的支付记录
        paylog_df = spark.sql(u"""
        SELECT
            jsonTable.userid as uid,
            jsonTable.accountid AS acid,
            jsonTable.gid AS gid,
            jsonTable.sid AS sid,
            jsonTable.channel AS ch,
            jsonTable.corplvl AS corpLvl,
            jsonTable.info.VipLvl AS vipLvl,
            jsonTable.info.Money AS payNum,
            jsonTable.info.PayTime AS payTime,
            SUBSTRING(jsonTable.logtime,0,10) AS LogTime,
            CAST(CAST(jsonTable.utc8 as DATE) as varchar(10)) AS date
        FROM jsonTable
        WHERE type_name = "IAP"
        """)
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish IAP"
        # 获取当日log里的最早的一次登录
        uidlogByChannel_df = spark.sql(u'''
                SELECT
                    t.uid AS uid,
                    SUBSTRING(t.lt,0,10) AS lt,
                    CAST(CAST(jsonTable.utc8 as DATE) as varchar(10)) AS date,
                    jsonTable.sid AS sid,
                    jsonTable.gid AS gid,
                    jsonTable.channel AS ch,
                    jsonTable.info.MachineType AS machine
                FROM (
                    SELECT
                        userid AS uid,
                        min(logtime) AS lt
                    FROM jsonTable
                    WHERE type_name="Login"
                    GROUP BY userid
                ) t
                LEFT JOIN jsonTable ON jsonTable.userid = t.uid AND jsonTable.logtime = t.lt
            ''')
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish uid Login"

        #读取createProfile
        uidlogNoChannel_df = spark.sql(u'''
                SELECT
                    t.uid AS uid,
                    SUBSTRING(t.lt,0,10) AS lt,
                    CAST(CAST(jsonTable.utc8 as DATE) as varchar(10)) AS date,
                    jsonTable.sid AS sid,
                    jsonTable.gid AS gid
                FROM (
                    SELECT
                        userid AS uid,
                        min(logtime) AS lt
                    FROM jsonTable
                    WHERE type_name="CreateProfile"
                    GROUP BY userid
                ) t
                LEFT JOIN jsonTable ON jsonTable.userid = t.uid AND jsonTable.logtime = t.lt
            ''')

        acidlogNoChannel_df = spark.sql(u'''
                SELECT
                    t.acid AS acid,
                    SUBSTRING(t.lt,0,10) AS lt,
                    CAST(CAST(jsonTable.utc8 as DATE) as varchar(10)) AS date,
                    jsonTable.sid AS sid,
                    jsonTable.gid AS gid
                FROM (
                    SELECT
                        accountid AS acid,
                        min(logtime) AS lt
                    FROM jsonTable
                    WHERE type_name="CreateProfile"
                    GROUP BY accountid
                ) t
                LEFT JOIN jsonTable ON jsonTable.accountid = t.acid AND jsonTable.logtime = t.lt
                ''')

        # 获取当日log里分服务器玩家角色的第一次登录
        acidlog_df = spark.sql(u'''
                SELECT
                    t.acid AS acid,
                    SUBSTRING(t.lt,0,10) AS lt,
                    CAST(CAST(jsonTable.utc8 as DATE) as varchar(10)) AS date,
                    jsonTable.sid AS sid,
                    jsonTable.gid AS gid,
                    jsonTable.channel AS ch,
                    jsonTable.info.MachineType AS machine
                FROM (
                    SELECT
                        accountid AS acid,
                        min(logtime) AS lt
                    FROM jsonTable
                    WHERE type_name="Login"
                    GROUP BY accountid
                ) t
                LEFT JOIN jsonTable ON jsonTable.accountid = t.acid AND jsonTable.logtime = t.lt
                ''')



        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish acid Login"


        false_channel = getFalesChannel()
        true_channel = getTrueChannel()
        # 替换channel
        uid_creatTimeBychannelLog = uidlogByChannel_df.replace(false_channel, true_channel, "ch")

        paylog_data = paylog_df.replace(false_channel, true_channel, "ch")


        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish all replace"
        print "uid Creat Time:"
        uid_creatTimeBychannelLog.show(3)
        print "acid Creat Time:"
        acidlogNoChannel_df.show(3)
        uidlogNoChannel_df.show(3)
        print "payLog:"
        paylog_data.show(3)
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish today data"
        # S3上读取中间数据
        #uid->creat time
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "union today uid_creatTime"

        #uid无Channel
        uidList = getTempDataList("uid_creatTime")
        if len(uidList) > 0:
            df_temp_uid = spark.read.json(uidList)
            #final_uid_Result = df_temp_uid.rdd.union(uidlogNoChannel_df.rdd).map(lambda x: (x.uid, x)).reduceByKey(min_time).values()
            print "union"
            qq = df_temp_uid.rdd.union(uidlogNoChannel_df.rdd)
            cc = qq.map(lambda x: (x.uid, x))
            print "reduceBykey"

            final_uid_Result = cc.reduceByKey(min_time).values()
            print final_uid_Result.collect()
            print type(final_uid_Result)
            
            schema =  StructType([
                StructField ("uid" , StringType(), True), 
                StructField("gid" , IntegerType(), True),
                StructField("sid" , IntegerType(), True),
                StructField("date" , StringType(), True),
                StructField("lt" , StringType(), True)])
            
            final_uid_Result_fream = spark.createDataFrame(final_uid_Result,schema)
            print "uidDataFreame collect"
            #print final_uid_Result_fream.collect()
            
            final_uid_Result_fream.createOrReplaceTempView('uidlog')

            xx = final_uid_Result_fream.toPandas()
            print "uidListMerge"
            print xx
            upload(xx, 'cn-north-1', "prodlog", '/%s/uid_creatTime.json' % target_path)
        else:
            uidlogNoChannel_df.createOrReplaceTempView('uidlog')
            upload(uidlogNoChannel_df.toPandas(),'cn-north-1', "prodlog", '/%s/uid_creatTime.json' % target_path)
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "union today uid_creatTime"


        #acid无channel
        acidList = getTempDataList("acid_creatTime")
        if len(acidList) > 0:
            df_temp_acid = spark.read.json(acidList)

            final_acid_Result = df_temp_acid.rdd.union(acidlogNoChannel_df.rdd).map(lambda x: (x.acid, x)).reduceByKey(min_time).values()
            final_acid_Result_fream = spark.createDataFrame(final_acid_Result)
            final_acid_Result_fream.createOrReplaceTempView('acidlog')

            xx = final_acid_Result_fream.toPandas()
            print "acidListMerge",xx
            upload(xx, 'cn-north-1', "prodlog", '/%s/acid_creatTime.json' % target_path)
        else:
            acidlogNoChannel_df.createOrReplaceTempView('acidlog')
            upload(acidlogNoChannel_df.toPandas(), 'cn-north-1', "prodlog", '/%s/acid_creatTime.json' % target_path)
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "union today acid_creatTime "

        #渠道
        ChannelList = getTempDataList("uid_ByChannelcreatTime")
        if len(ChannelList) > 0:
            df_temp_uidChannel = spark.read.json(acidList)

            final_uidChannel_Result = df_temp_uidChannel.rdd.union(uidlogByChannel_df.rdd).map(lambda x: (x.acid, x)).reduceByKey(
                min_time).values()
            final_uidChannel_Result_fream = spark.createDataFrame(final_uidChannel_Result)
            final_uidChannel_Result_fream.createOrReplaceTempView('uidChannelLog')

            xx = final_uidChannel_Result_fream.toPandas()
            print "channelListMerge",xx
            upload(xx, 'cn-north-1', "prodlog", '/%s/uid_ByChannelcreatTime.json' % target_path)
        else:
            uidlogByChannel_df.createOrReplaceTempView('uidChannelLog')
            upload(uidlogByChannel_df.toPandas(), 'cn-north-1', "prodlog", '/%s/uidChannelLog.json' % target_path)
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "union today uid_ByChannelcreatTime "

        # 处理支付log
        paylog_data_pd = paylog_data.toPandas()

        # 读取支付历史数据
        payList = getTempDataList("payLog")
        if len(payList) > 0:
            historyPayLog = spark.read.json(payList)
            result_pdf = paylog_data.union(historyPayLog)
            # 历史数据建立临时表
            result_pdf.createOrReplaceTempView('payLog')
            #上传支付log
            upload(paylog_data_pd, 'cn-north-1', "prodlog", '/%s_payLog.json' % (targetpay_path +day))
        else:
            paylog_data.createOrReplaceTempView('payLog')
            upload(paylog_data_pd, 'cn-north-1', "prodlog", '/%s_payLog.json' % (targetpay_path +day))


        spark.sql(u'''
                SELECT
                    uid AS uid,
                    SUM(payNum) AS sumpay,
                    gid AS gid
                FROM payLog
                GROUP BY gid,uid
                ''').createOrReplaceTempView('payByGid')

        spark.sql(u'''
                SELECT
                    acid AS acid,
                    SUM(payNum) AS sumpay,
                    sid AS sid
                FROM payLog
                GROUP BY sid,acid
                ''').createOrReplaceTempView('payBySid')

        spark.sql(u'''
                SELECT
                    uid AS uid,
                    SUM(payNum) AS sumpay,
                    ch AS ch
                FROM payLog
                GROUP BY ch,uid
                ''').createOrReplaceTempView('payByCh')

        # 查出账号创建时间
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "start ltv"
        cToday = datetime.date(int(pp[0]), int(pp[1]), int(pp[2]))
        for i in range((cToday - firstDay).days + 1):
            creatDay = u''' "%s"''' % str(firstDay + datetime.timedelta(days=i))
            creatDayDateTime = firstDay + datetime.timedelta(days=i)
            theday = (cToday - creatDayDateTime).days + 1
            payResultByGid = spark.sql(u'''
                                            SELECT
                                                s.gid AS gid,
                                                SUM(t.pay) AS payNum,
                                                COUNT(s.uid) AS people,
                                                first(s.date) AS date
                                            FROM(
                                            (SELECT
                                                uid AS uid,
                                                date AS date ,
                                                gid AS gid
                                            FROM uidlog
                                            WHERE date = %s) s
                                            LEFT OUTER JOIN(
                                            SELECT
                                                uid AS uid,
                                                sumpay AS pay,
                                                gid AS gid
                                            FROM payByGid
                                            ) t
                                            on t.uid = s.uid)
                                            GROUP BY s.gid
                                        ''' % creatDay)

            finalLTV_ByGid = payResultByGid.withColumn("days", payResultByGid.people - payResultByGid.people + theday)
            payResultBySid = spark.sql(u'''
                                            SELECT
                                                s.sid As sid,
                                                SUM(t.payNum) AS payNum,
                                                COUNT(s.acid) AS people,
                                                first(s.date) AS date
                                            FROM(
                                            (SELECT
                                                acid AS acid,
                                                date AS date,
                                                sid AS sid
                                            FROM acidlog
                                            WHERE date = %s) s
                                            LEFT OUTER JOIN(
                                            SELECT
                                                acid AS acid,
                                                sumpay AS payNum,
                                                sid AS sid
                                            FROM payBySid
                                            ) t
                                            on t.acid = s.acid)
                                            GROUP BY s.sid
                                        ''' % creatDay)

            finalLTV_BySid = payResultBySid.withColumn("days", payResultBySid.people - payResultBySid.people + theday)
            payResultByCh = spark.sql(u'''
                                            SELECT
                                                s.ch AS ch,
                                                SUM(t.pay) AS payNum,
                                                COUNT(s.uid) AS people,
                                                first(s.date)
                                            FROM(
                                            (SELECT
                                                uid AS uid,
                                                date AS date ,
                                                ch AS ch
                                            FROM uidChannelLog
                                            WHERE date = %s) s
                                            LEFT OUTER JOIN(
                                            SELECT
                                                uid AS uid,
                                                sumpay AS pay,
                                                ch AS ch
                                            FROM payByCh
                                            ) t
                                            on t.uid = s.uid)
                                            GROUP BY s.ch
                                        ''' % creatDay)

            finalLTV_ByCh = payResultByCh.withColumn("days", payResultByCh.people - payResultByCh.people + theday)

            payResultByGid_pd = finalLTV_ByGid.toPandas()
            payResultBySid_pd = finalLTV_BySid.toPandas()
            payResultByCh_pd = finalLTV_ByCh.toPandas()

            # 替换 nan
            payResultByGid_pd = payResultByGid_pd.where(payResultByGid_pd.notnull(), None)
            payResultBySid_pd = payResultBySid_pd.where(payResultBySid_pd.notnull(), None)
            payResultByCh_pd = payResultByCh_pd.where(payResultByCh_pd.notnull(), None)
            print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish today ltv,begin ->sql"
            ltv_byGid_sqlalchemy_orm(payResultByGid_pd)
            ltv_bySid_sqlalchemy_orm(payResultBySid_pd)
            ltv_byCh_sqlalchemy_orm(payResultByCh_pd)
        print time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time()))), "finish today data"

    spark.stop()

2017-06-28 12:14:59 creat spark session
2017-06-28 12:14:59 start: 20170201
2017-06-28 12:15:00 finish read original data
2017-06-28 12:15:00 finish creat today jsonTable
2017-06-28 12:15:00 finish IAP
2017-06-28 12:15:00 finish uid Login
2017-06-28 12:15:00 finish acid Login
2017-06-28 12:15:00 finish all replace
uid Creat Time:
+--------------------+----------+----------+----+---+------------+--------------------+
|                 uid|        lt|      date| sid|gid|          ch|             machine|
+--------------------+----------+----------+----+---+------------+--------------------+
|38420ce1-b171-4ee...|1485909512|2017-02-01|1001|200|130134005400|         Xiaomi MI 5|
|b4c12f87-3751-4c3...|1485913264|2017-02-01|1001|200|130134004600|YuLong Coolpad 86...|
|504717e5-384b-466...|1485919808|2017-02-01|1001|200|130134001500|         Meizu PRO 5|
+--------------------+----------+----------+----+---+------------+--------------------+
only showing top 3 rows

acid Creat Time:
+--------------------+----------+----------+----+---+
|                acid|        lt|      date| sid|gid|
+--------------------+----------+----------+----+---+
|200:1001:006c83d5...|1485915425|2017-02-01|1001|200|
|200:1001:8dea1830...|1485928256|2017-02-01|1001|200|
|200:1001:e9fa42f7...|1485958029|2017-02-01|1001|200|
+--------------------+----------+----------+----+---+
only showing top 3 rows

+--------------------+----------+----------+----+---+
|                 uid|        lt|      date| sid|gid|
+--------------------+----------+----------+----+---+
|697b6f94-2f7a-4e2...|1485946542|2017-02-01|1001|200|
|e842a215-2a8b-422...|1485966165|2017-02-02|1001|200|
|a6e03dd8-3851-405...|1485926135|2017-02-01|1001|200|
+--------------------+----------+----------+----+---+
only showing top 3 rows

payLog:
+--------------------+--------------------+---+----+------------+-------+------+------+--------------+----------+----------+
|                 uid|                acid|gid| sid|          ch|corpLvl|vipLvl|payNum|       payTime|   LogTime|      date|
+--------------------+--------------------+---+----+------------+-------+------+------+--------------+----------+----------+
|7a576463-90f9-420...|200:1001:7a576463...|200|1001|130134001300|     81|    11|   600|20170201075826|1485907229|2017-02-01|
|fcf736a7-abf4-44e...|200:1001:fcf736a7...|200|1001|        5000|     69|     6|   100|20170201081234|1485907988|2017-02-01|
|fcf736a7-abf4-44e...|200:1001:fcf736a7...|200|1001|        5000|     69|     6|  3000|20170201081332|1485908044|2017-02-01|
+--------------------+--------------------+---+----+------------+-------+------+------+--------------+----------+----------+
only showing top 3 rows

2017-06-28 12:15:01 finish today data
2017-06-28 12:15:01 union today uid_creatTime
[]
2017-06-28 12:15:01 union today uid_creatTime
[]
2017-06-28 12:15:02 union today acid_creatTime
[]
2017-06-28 12:15:02 union today uid_ByChannelcreatTime
[]
2017-06-28 12:15:03 start ltv
2017-06-28 12:15:03 finish today data
2017-06-28 12:15:03 start: 20170202
2017-06-28 12:15:03 finish read original data
2017-06-28 12:15:03 finish creat today jsonTable
2017-06-28 12:15:03 finish IAP
2017-06-28 12:15:03 finish uid Login
2017-06-28 12:15:03 finish acid Login
2017-06-28 12:15:03 finish all replace
uid Creat Time:
+--------------------+----------+----------+----+---+------------+--------------------+
|                 uid|        lt|      date| sid|gid|          ch|             machine|
+--------------------+----------+----------+----+---+------------+--------------------+
|504717e5-384b-466...|1485995478|2017-02-02|1001|200|130134001500|         Meizu PRO 5|
|38420ce1-b171-4ee...|1486007578|2017-02-02|1001|200|130134005400|         Xiaomi MI 5|
|c9b57475-3816-44a...|1486009039|2017-02-02|1001|200|130134001500|HUAWEI HUAWEI NXT...|
+--------------------+----------+----------+----+---+------------+--------------------+
only showing top 3 rows

acid Creat Time:
+--------------------+----------+----------+----+---+
|                acid|        lt|      date| sid|gid|
+--------------------+----------+----------+----+---+
|200:1001:8056ce7d...|1486046911|2017-02-02|1001|200|
|200:1001:c5181815...|1486002557|2017-02-02|1001|200|
|200:1001:10ee9747...|1486021301|2017-02-02|1001|200|
+--------------------+----------+----------+----+---+
only showing top 3 rows

+--------------------+----------+----------+----+---+
|                 uid|        lt|      date| sid|gid|
+--------------------+----------+----------+----+---+
|471ca065-e854-4d5...|1486000886|2017-02-02|1001|200|
|36322af9-7603-4a8...|1486042246|2017-02-02|1001|200|
|7fce27d1-7e3e-40e...|1485999708|2017-02-02|1001|200|
+--------------------+----------+----------+----+---+
only showing top 3 rows

payLog:
+--------------------+--------------------+---+----+------------+-------+------+------+--------------+----------+----------+
|                 uid|                acid|gid| sid|          ch|corpLvl|vipLvl|payNum|       payTime|   LogTime|      date|
+--------------------+--------------------+---+----+------------+-------+------+------+--------------+----------+----------+
|f73ef3ed-6acc-4bc...|200:1001:f73ef3ed...|200|1001|130134001300|     79|    11|   600|20170202080100|1485993691|2017-02-02|
|c920b03e-8011-494...|200:1001:c920b03e...|200|1001|130134001500|     30|     0|   600|20170202080324|1485993985|2017-02-02|
|e4b5d937-76ad-487...|200:1001:e4b5d937...|200|1001|130134001300|     72|     9|  2500|20170202080933|1485994227|2017-02-02|
+--------------------+--------------------+---+----+------------+-------+------+------+--------------+----------+----------+
only showing top 3 rows

2017-06-28 12:15:04 finish today data
2017-06-28 12:15:04 union today uid_creatTime
['/Users/tq/bigdatatest/uid_creatTime.json']
uidlogNoChannel_df
[Row(uid=u'471ca065-e854-4d5f-a6bb-31df5cc1d287', lt=u'1486000886', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'36322af9-7603-4a8d-8082-c19047e2dca3', lt=u'1486042246', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'7fce27d1-7e3e-40e9-9a17-949b828eac1b', lt=u'1485999708', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'76caf9b0-7668-453f-80ff-dded9ddef385', lt=u'1486012393', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'2b0efeb5-ae70-483e-9252-6a40fea29b28', lt=u'1486024837', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'917ba4a1-72db-4e81-b160-732d98d91f7d', lt=u'1486025426', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'5b439812-7099-41b3-a14e-9769ae6f61d3', lt=u'1486046704', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'f57301fc-07da-47fb-a983-54246ad0fea6', lt=u'1486031765', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'7dedd140-ba12-400a-80c4-d6065d7d9fc7', lt=u'1486043345', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'a61afe24-385a-4eaf-b125-e93e82d87fb0', lt=u'1486044409', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'3eb90575-7627-4c5f-aa65-4d4a233e6062', lt=u'1486038836', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'755b3dfa-ebda-4ee6-aa88-2347cd58ebdd', lt=u'1486044790', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'c89133b3-6769-4b3f-8700-6b3475be96cd', lt=u'1486040981', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'b4aace06-4e67-4666-b1c5-f3695359567b', lt=u'1486049559', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'4c84ba83-7103-4656-a7b4-49014d710cf6', lt=u'1486007536', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'9dc8e8a0-8af7-471a-9e58-bfb4d4de9bc5', lt=u'1486001099', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'c5181815-8751-4110-b4db-26a63e6209a9', lt=u'1486002557', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'a65a772a-b470-4b61-b350-19dde0e02188', lt=u'1486019818', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'5c4d7820-e97d-4ab6-b194-2f2fcd6c425d', lt=u'1486028027', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'3f1dc78e-b5c2-48fd-9b57-5ec99e973148', lt=u'1486031370', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'7a627ba3-db4d-4afe-ac37-7bea03349564', lt=u'1486021006', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'8343d30f-b767-4f2c-be40-cc4be52eed78', lt=u'1486001168', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'72af3047-d76e-49f8-b35b-5122c6ba7c20', lt=u'1485994718', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'1cbb30f8-8ddf-421a-8b3c-018631045ebc', lt=u'1486034017', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'8be68adf-dd51-4376-af40-1277218cc476', lt=u'1485995611', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'8056ce7d-86dd-4e7c-847c-370f2d742232', lt=u'1486046911', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'd322bff2-f643-46a6-9548-c8ed1d9cf1cf', lt=u'1486014197', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'326730d8-7eee-4244-85da-5c1b2404b215', lt=u'1486047651', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'a66dfb5c-859e-472b-b947-bdc060fdd0ea', lt=u'1486024655', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'eb41c3cc-774a-4fe3-b936-aa8368ab8a35', lt=u'1485996886', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'ec2410cf-c678-4382-a645-481bb7de0dc3', lt=u'1486027339', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'3246b44a-d6f3-430b-a7c1-061f52d3d3d1', lt=u'1486047301', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'c0b16477-1ee0-4270-96b9-06dacba1841d', lt=u'1486009416', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'4730de5f-9567-4c7f-a8ac-746c5c3e2b1d', lt=u'1486015854', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'7b8ecf51-435b-4f22-a1e0-8b99cec8fcdf', lt=u'1486011575', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'db0054c0-f989-44c6-9abc-a0a8aa0bd71b', lt=u'1485995411', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'f8b513bc-814c-4631-ad1c-75bc7302e12c', lt=u'1486047157', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'cdca9448-dc34-40bc-92ca-6c4bf2d90ae8', lt=u'1486029202', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'41a36401-6ea2-4f71-8482-e11b94700406', lt=u'1486029942', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'20db349a-3e2f-45c9-89ae-bfd1f93ea5d6', lt=u'1486006889', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'4612ebea-0c1d-4ad8-90d5-e9008813bc77', lt=u'1486037025', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'6b8b1bfd-879e-4315-baf9-3ece15619c64', lt=u'1485999449', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'cd15d774-e2d7-4551-83d6-567933dcdade', lt=u'1486006222', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'b937422c-217f-4a19-aaf5-06abdf860374', lt=u'1486005121', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'd9fde481-e002-43a0-8f04-f25276832171', lt=u'1486026868', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'4d56c397-947f-4ad9-9b8d-5f2fdb49c524', lt=u'1486008464', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'fe17628b-96de-4d3b-9230-34f7337ce8eb', lt=u'1486030216', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'81ee53bb-9cdd-4e95-8eb8-307f45add68e', lt=u'1486050144', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'c920ebb5-4a9b-4c3c-9ef3-d5320c846b7a', lt=u'1486016230', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'dc5dd6ef-af62-4f97-8d93-9e1fbc0495a3', lt=u'1486027193', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'0b73dff2-f6b1-4d79-ab9a-05a28148a2a1', lt=u'1486047550', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'36ee7eb7-3341-4014-8952-38257fbd6686', lt=u'1486043808', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'e8846b38-609f-4efd-a7a3-2ccfa9dc9669', lt=u'1486024993', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'85d95010-63ac-4b4e-a984-0c3bdfaeac92', lt=u'1486004525', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'5418698a-7297-4a4a-b592-1c151a1fdb61', lt=u'1486002300', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'de1f4afd-edd2-4ff8-8d42-7100f991f3d6', lt=u'1486032591', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'd5abc52e-f7a9-4743-9d32-d5fc3c1fe8ac', lt=u'1485996829', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'0fe8ccec-90a2-4d79-9dd1-4de59dd2fbd3', lt=u'1486040036', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'242ffa43-65f4-4333-a71e-1ed0d1c112c8', lt=u'1486042790', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'2d3cd828-7870-474c-a4c2-8a7bc920fe68', lt=u'1486037105', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'afd7334e-f251-4f01-b6bf-9dc0a83f2f28', lt=u'1485998530', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'd3ca056e-726a-4738-961a-3737bb41aa44', lt=u'1486032860', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'f2ef8ad9-cce1-41d4-a8c2-fcebac0cfcf2', lt=u'1485995523', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'2016e7c2-7265-4351-9cb7-fe049747f28e', lt=u'1486022065', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'ceb61bd5-93d8-4716-9f51-0fe6046bcba9', lt=u'1486015922', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'4c9de431-841e-4b55-83b5-3fb61d65d66a', lt=u'1486003719', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'e4186ecd-afa7-49a1-8ac5-8d1e30dbe79c', lt=u'1486025274', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'd19b75f3-d4de-4f01-a7b9-7b1f2cfd0b43', lt=u'1486028431', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'57d66a46-fd13-4340-8dbe-31890f928c6b', lt=u'1486054025', date=u'2017-02-03', sid=1001, gid=200), Row(uid=u'dc69b490-fd3a-49db-88a7-1b24777ec6b3', lt=u'1486020328', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'56070c49-ef1e-4d47-8412-9c593a9c8e97', lt=u'1486048767', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'd6690f08-8ff1-4f85-b9b4-c686e1def881', lt=u'1486033063', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'caafbbdd-b8c0-4a6f-b402-35f3022db354', lt=u'1486021024', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'8b9c4d94-2330-49ba-9fc1-913567f865ba', lt=u'1486008057', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'8ff67a49-2245-4ff1-9e7c-9a05bc287f24', lt=u'1486050976', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'15d0910d-ceac-47bc-b8d7-c9c187c54220', lt=u'1486020253', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'7965c7f3-abca-45d9-a18a-2f180c1672d5', lt=u'1486056227', date=u'2017-02-03', sid=1001, gid=200), Row(uid=u'72e75e85-ec4b-4fdb-8877-df570b3fdac7', lt=u'1486039292', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'87524976-3c54-45bb-9482-1391b81aad44', lt=u'1486011590', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'bc614958-6b77-482c-92b5-144cac87b63f', lt=u'1486026685', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'ec8b27a4-ec2b-4728-9b15-71cccfa98349', lt=u'1486032925', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'210ace43-0e60-4897-9b6e-44da7df65996', lt=u'1486013176', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'10ee9747-d18f-4c68-b286-00719aca6f3c', lt=u'1486021301', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'c11e7a34-03ea-4ada-bf03-d74d73bd780f', lt=u'1486032041', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'723625e0-449e-4232-b13c-1896a019affd', lt=u'1486005485', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'be80830a-e4e7-4510-a3fb-833535aac599', lt=u'1486024403', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'82c80635-c99b-4834-9ea7-9bf7995ca2f2', lt=u'1486029953', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'ac439c4d-d529-4549-b774-bdad218002d0', lt=u'1486036644', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'ac0c133b-6749-4add-b381-fb19aabd64da', lt=u'1486004891', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'09e9b550-dae7-44c6-bdb0-9571f543ba5b', lt=u'1486040301', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'd4c87387-fb97-49f6-ace9-ab5bdd62545d', lt=u'1486006285', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'e5d9d694-6602-410d-a3d0-62f58ec3a045', lt=u'1486009673', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'9c375f46-3cb3-4bda-ac2d-f28e230d6f08', lt=u'1486026007', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'9b0ad62e-1ca0-4b45-a0e5-66238f1104c6', lt=u'1486023537', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'731adf4e-3628-4e54-ade4-b0acff7d3c7e', lt=u'1486008911', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'bc649ab8-d4aa-4ae4-b32f-71ee9dc88086', lt=u'1486038993', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'6325bb44-e168-4f68-a3d2-99df2e6f4486', lt=u'1485997350', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'618f1db0-457f-47f6-a85b-3a91d4a29151', lt=u'1486014075', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'11e4ce68-9f13-4712-a130-623c3fbeb81f', lt=u'1486040242', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'8e4fcab8-6e95-413c-9349-f28dbb5c4b1f', lt=u'1486012383', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'b629125a-ab8f-4ffe-94f9-e92fe8cd3803', lt=u'1486036450', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'41d7fd51-300c-469f-bee2-89e01f3715d2', lt=u'1486047986', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'0fb2f82c-5940-4f4b-a989-36710d63ec7e', lt=u'1486034677', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'4bc3796b-9155-49ff-a384-96e8259b45ad', lt=u'1486043979', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'6da5b45f-2195-4efe-aef7-0cb650ba501b', lt=u'1486042627', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'0ae9dee5-ea25-4b09-ab99-fd5bd1b8f9ad', lt=u'1486023110', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'e6587376-0b51-4009-b6a5-69d7ee3bdb18', lt=u'1486004206', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'1c2a984c-1201-4ba4-a35e-f2d3dbe520e4', lt=u'1486005599', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'a05235d9-9be5-499f-9c4f-fa3238789beb', lt=u'1486041673', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'5deb51cb-8ffb-434c-9a18-7694bfc94181', lt=u'1486021222', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'3850314a-2bff-4ffc-86ef-3c93ae12f0a7', lt=u'1486019541', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'061065fb-c56d-4e82-bdff-73cddb427470', lt=u'1486023146', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'7b714ff6-c204-4345-9903-635e0db72104', lt=u'1486057143', date=u'2017-02-03', sid=1001, gid=200), Row(uid=u'4ddd4eb0-9f14-4c3e-96ff-605703c46242', lt=u'1486024809', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'9156b312-d191-46cf-bc4c-f8177307f2c3', lt=u'1486035411', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'5301e804-8282-47a1-97da-7922c24e0d00', lt=u'1486076970', date=u'2017-02-03', sid=1001, gid=200), Row(uid=u'd56375d4-ed4f-4519-a7e0-24f6f1c2ce04', lt=u'1486003499', date=u'2017-02-02', sid=1001, gid=200), Row(uid=u'a3475e17-6f92-4cf3-be8c-ec46ca154028', lt=u'1486026466', date=u'2017-02-02', sid=1001, gid=200)]
union
reduceBykey

Py4JJavaError: An error occurred while calling o4584.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 1826.0 failed 1 times, most recent failure: Lost task 2.0 in stage 1826.0 (TID 41626, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 174, in main
    process()
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 169, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/pyspark/sql/session.py", line 509, in prepare
    verify_func(obj, schema)
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1360, in _verify_type
    _verify_type(v, f.dataType, f.nullable)
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1324, in _verify_type
    raise TypeError("%s can not accept object %r in type %s" % (dataType, obj, type(obj)))
TypeError: IntegerType can not accept object u'1486041673' in type <type 'unicode'>

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1925)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1938)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1951)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1965)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:935)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:275)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply$mcI$sp(Dataset.scala:2768)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:2765)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:2765)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2788)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:2765)
	at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 174, in main
    process()
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/worker.py", line 169, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/pyspark/sql/session.py", line 509, in prepare
    verify_func(obj, schema)
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1360, in _verify_type
    _verify_type(v, f.dataType, f.nullable)
  File "/Users/tq/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/types.py", line 1324, in _verify_type
    raise TypeError("%s can not accept object %r in type %s" % (dataType, obj, type(obj)))
TypeError: IntegerType can not accept object u'1486041673' in type <type 'unicode'>

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more