In [95]:
# -*- coding:utf-8 -*-
import pandas as pd
import codecs
import json
import io
import StringIO
from pandas.io.json import json_normalize

In [96]:
with open('/Users/tq/Downloads/logics_pay.10.11.2016.log', 'r') as json_data:
    json_buffer = StringIO.StringIO()
    for line in json_data:
        tempMap = {}
        json_dicts = json.loads(line)  # 读取json数据为list[dict]结构
        tempMap.setdefault('sid',json_dicts['sid'])
        tempMap.setdefault('acid',json_dicts['accountid'])
        tempMap.setdefault('Money',json_dicts['info']['Money'])
        tempMap.setdefault('PayTime',json_dicts['utc8'][0:10])
        json_temp = json.dumps(tempMap)
        json_buffer.writelines(json_temp+"\n")

In [97]:
pay = pd.read_json(json_buffer.getvalue(),lines=True)

In [98]:
pay

       Money     PayTime                                           acid   sid
0          1  2016-11-11  200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21  1001
1          6  2016-11-15  200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55  1013
2          6  2016-11-15  200:1009:1337f849-a408-4a05-bcde-d941315d0ba1  1009
3         25  2016-11-11  200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd  1003
4        328  2016-11-12  200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676  1005
5         30  2016-11-11  200:1001:58a95093-15d6-4261-9151-b6dd03029f3e  1001
6         98  2016-11-13  200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87  1009
7          6  2016-11-13  200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220  1001
8          6  2016-11-15  200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953  1012
9          6  2016-11-15  200:1004:82143338-3495-46b0-b00d-fe84a7c94225  1004
10         1  2016-11-14  200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff  1010
11         1  2016-11-12  200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e  1002
12         6  2016-11-12  200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9  1001
13        98  2016-11-14  200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b  1003
14        68  2016-11-18  200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2  1015
15        30  2016-11-13  200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16  1006
16         6  2016-11-17  200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9  1005
17        68  2016-11-10  200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268  1001
18        30  2016-11-12  200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be  1002
19         6  2016-11-11  200:1001:3039ef63-1524-46cf-ba49-9188aa081002  1001
20       648  2016-11-10  200:1004:87614525-f38c-43ce-a153-60ef0e2f1578  1004
21        25  2016-11-11  200:1001:0d39521a-4a45-480c-8772-7c24225c6c48  1001
22         6  2016-11-11  200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b  1002
23         6  2016-11-10  200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b  1001
24         1  2016-11-12  200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97  1003
25         6  2016-11-10  200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027  1001
26         6  2016-11-13  200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3  1006
27         6  2016-11-12  200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3  1004
28         6  2016-11-10  200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153  1001
29        25  2016-11-14  200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee  1011
...      ...         ...                                            ...   ...
57660      6  2016-11-18  200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98  1005
57661      1  2016-11-13  200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7  1002
57662     30  2016-11-13  200:1009:806567a1-8565-423f-8e04-42cf1b4dade6  1009
57663     68  2016-11-16  200:1013:85db0143-369d-4351-8698-4842eb50534f  1013
57664      6  1970-01-01  200:1010:aafe8ff2-029d-4a77-b395-af0de514df88  1010
57665     30  2016-11-14  200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b  1012
57666      6  2016-11-10  200:1003:32c155c7-050a-440b-968a-a5000e6add3c  1003
57667      1  2016-11-10  200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b  1001
57668     25  2016-11-13  200:1011:1369c61f-b375-4bf8-bb11-b9220301362e  1011
57669      6  2016-11-11  200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f  1004
57670     68  2016-11-14  200:1011:714f9a06-decc-402b-8e49-3205bf97ba31  1011
57671     25  2016-11-16  200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea  1003
57672     68  2016-11-12  200:1002:95940643-2054-48db-b352-25060ddf191e  1002
57673      6  2016-11-13  200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702  1009
57674     30  2016-11-12  200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d  1007
57675      6  2016-11-13  200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a  1010
57676      6  2016-11-15  200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40  1011
57677      1  2016-11-14  200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff  1010
57678     30  2016-11-15  200:1004:36f79246-bb89-483a-be3b-630c6f4e1032  1004
57679     68  2016-11-13  200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850  1008
57680      6  2016-11-14  200:1004:17926a73-59eb-4467-89f1-9e9978a019dc  1004
57681     30  2016-11-13  200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e  1008
57682     30  2016-11-17  200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea  1013
57683      1  2016-11-12  200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724  1006
57684      1  2016-11-11  200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598  1005
57685      6  2016-11-15  200:1006:0875ee8b-2319-4458-b85a-031760c5535f  1006
57686      6  2016-11-17  200:1011:312fda94-6cfc-4299-9b63-6964df5b224a  1011
57687     30  2016-11-17  200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333  1015
57688      1  2016-11-10  200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7  1001
57689      1  2016-11-13  200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df  1009

[57690 rows x 4 columns]

In [151]:
pay2 = pd.read_json('/Users/tq/Downloads/20161110_paylog.json')

In [152]:
pay2.rename(columns={'payNum': 'Money','date':'PayTime'}, inplace=True)

In [155]:
ss = pay2[['Money','PayTime','acid','sid']]

In [99]:
acidBysid = pd.read_json('/Users/tq/Downloads/acid_creatTime.json')
acid_temp = acidBysid[['acid','date','sid']]

In [100]:
acid_temp

                                                 acid       date   sid
0       202:3017:da90f57d-4b5b-4194-832d-434a4ee268df 2016-11-26  3017
1       200:1029:d866a3d1-3560-48f7-8fb3-a9601f3469c2 2016-11-30  1029
2       202:3002:22309af3-44fc-48d6-9a1f-f52260c147bd 2016-11-10  3002
3       200:1015:5d970ac2-3321-418a-80ca-10abbcf7ed76 2016-11-17  1015
4       202:3003:d5986731-e44f-470c-b196-75b8f2dba7af 2016-11-11  3003
5       200:1011:8756b871-4737-4d63-a2f9-f06e4e2f3cc7 2016-11-13  1011
6       200:1019:e032528b-4727-4d4f-8a3e-6fc672366ee1 2016-11-20  1019
7       200:1008:8aa19ac7-c4c1-4a6b-8d25-e1a5368ca357 2016-11-12  1008
8       201:2003:9c48983c-4755-48a0-a3f1-28d77645c858 2016-11-11  2003
9       202:3012:29482532-6839-4f96-90cc-2f30660374eb 2016-11-21  3012
10      200:1018:4900cafb-1614-4632-ba27-0fa374914c8a 2016-11-19  1018
11      200:1010:e7e9d6fa-1ca7-4cbe-85c7-255eedf59fcb 2016-11-13  1010
12      201:2011:cdaa70ce-0164-4ac9-9bd4-198d6d65e9e7 2016-11-23  2011
13      200:1011:caa7e99a-fabb-46d6-a325-6c2af753f7b4 2016-11-13  1011
14      201:2001:67242ce9-506a-4a8b-9c9b-7cfca7081f81 2016-11-26  2001
15      200:1001:5c0d6e07-8be5-41c6-802a-227f38ab17b9 2016-11-10  1001
16      202:3018:89664838-79e9-4f69-9461-5608cf6edde6 2016-11-26  3018
17      200:1019:a6f6a5ee-4733-4b06-9ceb-1fc99cda3213 2016-11-20  1019
18      200:1001:e5ee4898-b70b-4722-9082-2c75d897609c 2016-11-10  1001
19      200:1004:faa35b41-2edc-4c6e-a2eb-6aae2424a841 2016-11-10  1004
20      202:3016:ab124dcb-f2d0-46e5-82d0-0cbc637f52cf 2016-11-25  3016
21      200:1011:226033cd-c75b-428d-a3dc-24a63200ef20 2016-11-13  1011
22      200:1010:6482e2b0-7e61-475f-94bf-2a85de8607dd 2016-11-17  1010
23      200:1014:97e40a62-9bd5-44c1-811e-c254982970de 2016-11-17  1014
24      200:1020:1cca52e7-35aa-4d57-b78b-1f1a2955e401 2016-11-21  1020
25      200:1021:4e9464d2-e645-431a-9dc6-cbe53ac5dc7a 2016-11-22  1021
26      200:1027:03e1aa30-1735-4e2d-a623-1bc5213f6ab4 2016-11-28  1027
27      202:3004:0822a118-f473-45be-b6c2-6069756240c2 2016-11-14  3004
28      200:1019:a368c7ab-accb-4b13-8b2e-c2a7f8789cba 2016-11-20  1019
29      202:3012:7f1b08b5-6c86-4ec2-9072-976e1d2866f3 2016-11-21  3012
...                                               ...        ...   ...
823001  202:3018:fccd9494-0ce9-4f53-9913-fb361145a794 2016-11-26  3018
823002  200:1001:f618b4ba-5125-4a18-96c1-bd60d1326b0d 2016-11-20  1001
823003  200:1014:b61b5c95-e674-4f73-8371-87ab4d15bd66 2016-11-16  1014
823004  202:3014:50fdf635-0656-48cd-8c7f-16f6fcc411f4 2016-11-23  3014
823005  200:1018:479c7b96-e900-4bfa-9735-43a616bfad88 2016-11-20  1018
823006  200:1001:12b3bd27-9bf7-4011-a004-e37cb1a9e50c 2016-11-10  1001
823007  201:2002:ece2b19e-3840-466b-97c7-88e4385d171d 2016-11-11  2002
823008  202:3002:cf0c6285-41fd-4ef4-8535-45688fe86a5c 2016-11-10  3002
823009  201:2002:ba1dcb08-5db6-4faa-bcbd-30a599627916 2016-11-11  2002
823010  202:3007:b223d2c8-0d07-46d4-be97-05e6ab0450df 2016-11-17  3007
823011  202:3002:2670f837-e20d-45d5-b713-33c7b0593aa1 2016-11-10  3002
823012  200:1003:09c9051b-d86b-49d7-a3aa-588d5367a97b 2016-11-10  1003
823013  202:3012:0b871b4f-e735-436c-baed-c901ab9e85ad 2016-11-21  3012
823014  201:2004:9a222d63-13c9-491d-8e7b-54e2cccc5436 2016-11-12  2004
823015  202:3008:099ccd3a-70c6-4619-8345-9d780ba61e97 2016-11-18  3008
823016  202:3018:3af96e05-bb96-4f57-992d-a738ad46ea13 2016-11-27  3018
823017  200:1013:cfa17afb-e87d-4881-b386-4929984aa342 2016-11-15  1013
823018  201:2002:088e7c04-b23a-4c0e-ab46-7b03ff1be0ab 2016-11-11  2002
823019  202:3015:0dd14b77-d673-4479-a5aa-ea91072b6cfb 2016-11-24  3015
823020  200:1029:feccad2f-5c2f-4107-a184-9173f00b8110 2016-11-30  1029
823021  200:1021:9b1ec22e-8278-4d24-915e-c034cd652b3e 2016-11-22  1021
823022  202:3005:9dbbb8c1-3c5b-4c21-b664-9c108c47941c 2016-11-15  3005
823023  200:1020:d71666df-b98d-4911-bdfb-f0f5c77d7051 2016-11-21  1020
823024  201:2002:94c6d7c9-c5f2-4649-82be-76d6c24164a8 2016-11-11  2002
823025  200:1012:cc6935f8-27f0-4b33-b4cc-7c51033b0ea4 2016-11-15  1012
823026  202:3020:6a97f2f2-3744-4fab-882d-7e388d08bb59 2016-11-28  3020
823027  202:3017:51f0b1c9-b5ea-4f8e-a846-a9001161e883 2016-11-26  3017
823028  201:2010:23947156-44b3-4bcc-a3ff-de2a2c2ed05e 2016-11-19  2010
823029  200:1024:13764adb-51db-4f87-9715-7df73fa018de 2016-11-25  1024
823030  201:2006:204ad5e1-709f-4411-a946-b4601dee0866 2016-11-13  2006

[823031 rows x 3 columns]

In [101]:
creatGroup = acid_temp.groupby([acid_temp['date'],acid_temp['sid']]).count()

In [104]:
creatGroup.reset_index(inplace=True)

In [106]:
creatGroup.rename(columns={'acid':'peopleCount'}, inplace = True)

In [107]:
 payMerge = pay.merge(acid_temp, left_on='acid', right_on='acid', how='left',suffixes=['', '_r'])

In [108]:
payMerge

,Money,PayTime,acid,sid,date,sid_r
0,1,2016-11-11,200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21,1001,2016-11-11,1001.0
1,6,2016-11-15,200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55,1013,2016-11-15,1013.0
2,6,2016-11-15,200:1009:1337f849-a408-4a05-bcde-d941315d0ba1,1009,2016-11-12,1009.0
3,25,2016-11-11,200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd,1003,2016-11-10,1003.0
4,328,2016-11-12,200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676,1005,2016-11-11,1005.0
5,30,2016-11-11,200:1001:58a95093-15d6-4261-9151-b6dd03029f3e,1001,2016-11-10,1001.0
6,98,2016-11-13,200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87,1009,2016-11-13,1009.0
7,6,2016-11-13,200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220,1001,2016-11-10,1001.0
8,6,2016-11-15,200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953,1012,2016-11-14,1012.0
9,6,2016-11-15,200:1004:82143338-3495-46b0-b00d-fe84a7c94225,1004,2016-11-11,1004.0
10,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0
11,1,2016-11-12,200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e,1002,2016-11-10,1002.0
12,6,2016-11-12,200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9,1001,2016-11-10,1001.0
13,98,2016-11-14,200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b,1003,2016-11-10,1003.0
14,68,2016-11-18,200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,1015,2016-11-17,1015.0
15,30,2016-11-13,200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,1006,2016-11-12,1006.0
16,6,2016-11-17,200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,1005,2016-11-11,1005.0
17,68,2016-11-10,200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268,1001,2016-11-10,1001.0
18,30,2016-11-12,200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be,1002,2016-11-12,1002.0
19,6,2016-11-11,200:1001:3039ef63-1524-46cf-ba49-9188aa081002,1001,2016-11-10,1001.0
20,648,2016-11-10,200:1004:87614525-f38c-43ce-a153-60ef0e2f1578,1004,2016-11-10,1004.0
21,25,2016-11-11,200:1001:0d39521a-4a45-480c-8772-7c24225c6c48,1001,2016-11-10,1001.0
22,6,2016-11-11,200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b,1002,2016-11-10,1002.0
23,6,2016-11-10,200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b,1001,2016-11-10,1001.0
24,1,2016-11-12,200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97,1003,2016-11-10,1003.0
25,6,2016-11-10,200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027,1001,2016-11-10,1001.0
26,6,2016-11-13,200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3,1006,2016-11-11,1006.0
27,6,2016-11-12,200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3,1004,2016-11-10,1004.0
28,6,2016-11-10,200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153,1001,2016-11-10,1001.0
29,25,2016-11-14,200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee,1011,2016-11-14,1011.0
...,...,...,...,...,...,...
57660,6,2016-11-18,200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98,1005,2016-11-11,1005.0
57661,1,2016-11-13,200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7,1002,2016-11-10,1002.0
57662,30,2016-11-13,200:1009:806567a1-8565-423f-8e04-42cf1b4dade6,1009,2016-11-12,1009.0
57663,68,2016-11-16,200:1013:85db0143-369d-4351-8698-4842eb50534f,1013,2016-11-15,1013.0
57664,6,1970-01-01,200:1010:aafe8ff2-029d-4a77-b395-af0de514df88,1010,2016-11-13,1010.0
57665,30,2016-11-14,200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,1012,2016-11-14,1012.0
57666,6,2016-11-10,200:1003:32c155c7-050a-440b-968a-a5000e6add3c,1003,2016-11-10,1003.0
57667,1,2016-11-10,200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b,1001,2016-11-10,1001.0
57668,25,2016-11-13,200:1011:1369c61f-b375-4bf8-bb11-b9220301362e,1011,2016-11-13,1011.0
57669,6,2016-11-11,200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,1004,2016-11-10,1004.0
57670,68,2016-11-14,200:1011:714f9a06-decc-402b-8e49-3205bf97ba31,1011,2016-11-13,1011.0
57671,25,2016-11-16,200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea,1003,2016-11-10,1003.0
57672,68,2016-11-12,200:1002:95940643-2054-48db-b352-25060ddf191e,1002,2016-11-10,1002.0
57673,6,2016-11-13,200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702,1009,2016-11-13,1009.0
57674,30,2016-11-12,200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d,1007,2016-11-12,1007.0
57675,6,2016-11-13,200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a,1010,2016-11-13,1010.0
57676,6,2016-11-15,200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40,1011,2016-11-13,1011.0
57677,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0
57678,30,2016-11-15,200:1004:36f79246-bb89-483a-be3b-630c6f4e1032,1004,2016-11-10,1004.0
57679,68,2016-11-13,200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,1008,2016-11-12,1008.0
57680,6,2016-11-14,200:1004:17926a73-59eb-4467-89f1-9e9978a019dc,1004,2016-11-11,1004.0
57681,30,2016-11-13,200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e,1008,2016-11-12,1008.0
57682,30,2016-11-17,200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea,1013,2016-11-15,1013.0
57683,1,2016-11-12,200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724,1006,2016-11-11,1006.0
57684,1,2016-11-11,200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598,1005,2016-11-11,1005.0
57685,6,2016-11-15,200:1006:0875ee8b-2319-4458-b85a-031760c5535f,1006,2016-11-12,1006.0
57686,6,2016-11-17,200:1011:312fda94-6cfc-4299-9b63-6964df5b224a,1011,2016-11-13,1011.0
57687,30,2016-11-17,200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333,1015,2016-11-17,1015.0
57688,1,2016-11-10,200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,1001,2016-11-10,1001.0
57689,1,2016-11-13,200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,1009,2016-11-12,1009.0

In [109]:
finalpayMerge = pd.merge(payMerge,creatGroup,on=['date','sid'],how='left')

In [110]:
finalpayMerge

,Money,PayTime,acid,sid,date,sid_r,index,peopleCount
0,1,2016-11-11,200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21,1001,2016-11-11,1001.0,7.0,2088.0
1,6,2016-11-15,200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55,1013,2016-11-15,1013.0,95.0,12914.0
2,6,2016-11-15,200:1009:1337f849-a408-4a05-bcde-d941315d0ba1,1009,2016-11-12,1009.0,27.0,4850.0
3,25,2016-11-11,200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd,1003,2016-11-10,1003.0,2.0,17578.0
4,328,2016-11-12,200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676,1005,2016-11-11,1005.0,11.0,10764.0
5,30,2016-11-11,200:1001:58a95093-15d6-4261-9151-b6dd03029f3e,1001,2016-11-10,1001.0,0.0,12353.0
6,98,2016-11-13,200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87,1009,2016-11-13,1009.0,45.0,6877.0
7,6,2016-11-13,200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220,1001,2016-11-10,1001.0,0.0,12353.0
8,6,2016-11-15,200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953,1012,2016-11-14,1012.0,70.0,10656.0
9,6,2016-11-15,200:1004:82143338-3495-46b0-b00d-fe84a7c94225,1004,2016-11-11,1004.0,10.0,5103.0
10,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0,46.0,11970.0
11,1,2016-11-12,200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e,1002,2016-11-10,1002.0,1.0,12406.0
12,6,2016-11-12,200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9,1001,2016-11-10,1001.0,0.0,12353.0
13,98,2016-11-14,200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b,1003,2016-11-10,1003.0,2.0,17578.0
14,68,2016-11-18,200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,1015,2016-11-17,1015.0,154.0,9414.0
15,30,2016-11-13,200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,1006,2016-11-12,1006.0,24.0,6723.0
16,6,2016-11-17,200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,1005,2016-11-11,1005.0,11.0,10764.0
17,68,2016-11-10,200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268,1001,2016-11-10,1001.0,0.0,12353.0
18,30,2016-11-12,200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be,1002,2016-11-12,1002.0,20.0,263.0
19,6,2016-11-11,200:1001:3039ef63-1524-46cf-ba49-9188aa081002,1001,2016-11-10,1001.0,0.0,12353.0
20,648,2016-11-10,200:1004:87614525-f38c-43ce-a153-60ef0e2f1578,1004,2016-11-10,1004.0,3.0,18604.0
21,25,2016-11-11,200:1001:0d39521a-4a45-480c-8772-7c24225c6c48,1001,2016-11-10,1001.0,0.0,12353.0
22,6,2016-11-11,200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b,1002,2016-11-10,1002.0,1.0,12406.0
23,6,2016-11-10,200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b,1001,2016-11-10,1001.0,0.0,12353.0
24,1,2016-11-12,200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97,1003,2016-11-10,1003.0,2.0,17578.0
25,6,2016-11-10,200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027,1001,2016-11-10,1001.0,0.0,12353.0
26,6,2016-11-13,200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3,1006,2016-11-11,1006.0,12.0,13456.0
27,6,2016-11-12,200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3,1004,2016-11-10,1004.0,3.0,18604.0
28,6,2016-11-10,200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153,1001,2016-11-10,1001.0,0.0,12353.0
29,25,2016-11-14,200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee,1011,2016-11-14,1011.0,69.0,7061.0
...,...,...,...,...,...,...,...,...
57660,6,2016-11-18,200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98,1005,2016-11-11,1005.0,11.0,10764.0
57661,1,2016-11-13,200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7,1002,2016-11-10,1002.0,1.0,12406.0
57662,30,2016-11-13,200:1009:806567a1-8565-423f-8e04-42cf1b4dade6,1009,2016-11-12,1009.0,27.0,4850.0
57663,68,2016-11-16,200:1013:85db0143-369d-4351-8698-4842eb50534f,1013,2016-11-15,1013.0,95.0,12914.0
57664,6,1970-01-01,200:1010:aafe8ff2-029d-4a77-b395-af0de514df88,1010,2016-11-13,1010.0,46.0,11970.0
57665,30,2016-11-14,200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,1012,2016-11-14,1012.0,70.0,10656.0
57666,6,2016-11-10,200:1003:32c155c7-050a-440b-968a-a5000e6add3c,1003,2016-11-10,1003.0,2.0,17578.0
57667,1,2016-11-10,200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b,1001,2016-11-10,1001.0,0.0,12353.0
57668,25,2016-11-13,200:1011:1369c61f-b375-4bf8-bb11-b9220301362e,1011,2016-11-13,1011.0,47.0,5927.0
57669,6,2016-11-11,200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,1004,2016-11-10,1004.0,3.0,18604.0
57670,68,2016-11-14,200:1011:714f9a06-decc-402b-8e49-3205bf97ba31,1011,2016-11-13,1011.0,47.0,5927.0
57671,25,2016-11-16,200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea,1003,2016-11-10,1003.0,2.0,17578.0
57672,68,2016-11-12,200:1002:95940643-2054-48db-b352-25060ddf191e,1002,2016-11-10,1002.0,1.0,12406.0
57673,6,2016-11-13,200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702,1009,2016-11-13,1009.0,45.0,6877.0
57674,30,2016-11-12,200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d,1007,2016-11-12,1007.0,25.0,11331.0
57675,6,2016-11-13,200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a,1010,2016-11-13,1010.0,46.0,11970.0
57676,6,2016-11-15,200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40,1011,2016-11-13,1011.0,47.0,5927.0
57677,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0,46.0,11970.0
57678,30,2016-11-15,200:1004:36f79246-bb89-483a-be3b-630c6f4e1032,1004,2016-11-10,1004.0,3.0,18604.0
57679,68,2016-11-13,200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,1008,2016-11-12,1008.0,26.0,11722.0
57680,6,2016-11-14,200:1004:17926a73-59eb-4467-89f1-9e9978a019dc,1004,2016-11-11,1004.0,10.0,5103.0
57681,30,2016-11-13,200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e,1008,2016-11-12,1008.0,26.0,11722.0
57682,30,2016-11-17,200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea,1013,2016-11-15,1013.0,95.0,12914.0
57683,1,2016-11-12,200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724,1006,2016-11-11,1006.0,12.0,13456.0
57684,1,2016-11-11,200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598,1005,2016-11-11,1005.0,11.0,10764.0
57685,6,2016-11-15,200:1006:0875ee8b-2319-4458-b85a-031760c5535f,1006,2016-11-12,1006.0,24.0,6723.0
57686,6,2016-11-17,200:1011:312fda94-6cfc-4299-9b63-6964df5b224a,1011,2016-11-13,1011.0,47.0,5927.0
57687,30,2016-11-17,200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333,1015,2016-11-17,1015.0,154.0,9414.0
57688,1,2016-11-10,200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,1001,2016-11-10,1001.0,0.0,12353.0
57689,1,2016-11-13,200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,1009,2016-11-12,1009.0,27.0,4850.0

In [94]:
result = finalpayMerge.groupby([finalpayMerge['sid'],finalpayMerge['date'],finalpayMerge['PayTime'],finalpayMerge['peopleCount']]).sum()

In [64]:
result

                                     Money      sid_r
sid  date       PayTime    acid_y
1001 2016-11-10 1970-01-01 12353.0      75     3003.0
                2016-11-10 12353.0  123312  3629626.0
                2016-11-11 12353.0   48985  1092091.0
                2016-11-12 12353.0   22693   592592.0
                2016-11-13 12353.0   20406   447447.0
                2016-11-14 12353.0    6595   282282.0
                2016-11-15 12353.0    8432   223223.0
                2016-11-16 12353.0    6989   158158.0
                2016-11-17 12353.0    2042   115115.0
                2016-11-18 12353.0     522    59059.0
     2016-11-11 2016-11-11 2088.0     2941   188188.0
                2016-11-12 2088.0     2802    98098.0
                2016-11-13 2088.0      831    30030.0
                2016-11-14 2088.0      438    17017.0
                2016-11-15 2088.0      666    15015.0
                2016-11-16 2088.0       14     4004.0
                2016-11-17 2088.0      135     9009.0
     2016-11-12 1970-01-01 2169.0        2     2002.0
                2016-11-12 2169.0     6764   114114.0
                2016-11-13 2169.0     1282    54054.0
                2016-11-14 2169.0      663    25025.0
                2016-11-15 2169.0      647    24024.0
                2016-11-16 2169.0      215    16016.0
                2016-11-17 2169.0      332    15015.0
                2016-11-18 2169.0       80     3003.0
     2016-11-13 2016-11-13 1394.0     1122    59059.0
                2016-11-14 1394.0     1023    64064.0
                2016-11-15 1394.0      543    26026.0
                2016-11-16 1394.0      318    14014.0
                2016-11-17 1394.0       67     4004.0
...                                    ...        ...
1013 2016-11-15 2016-11-16 12914.0   55990   882323.0
                2016-11-17 12914.0   16209   404187.0
                2016-11-18 12914.0    1982    54702.0
     2016-11-16 1970-01-01 3258.0      205     4052.0
                2016-11-16 3258.0     9304   450785.0
                2016-11-17 3258.0     4974   133716.0
                2016-11-18 3258.0      381    15195.0
     2016-11-17 2016-11-17 61.0        648     1013.0
                2016-11-18 61.0         99     3039.0
1014 2016-11-16 1970-01-01 10668.0      90    18252.0
                2016-11-16 10668.0   53705  1302990.0
                2016-11-17 10668.0   24937   750360.0
                2016-11-18 10668.0    3147    82134.0
     2016-11-17 1970-01-01 2968.0        1     1014.0
                2016-11-17 2968.0    10651   350844.0
                2016-11-18 2968.0      659    27378.0
1015 2016-11-17 1970-01-01 9414.0      136     2030.0
                2016-11-17 9414.0    77134  1126650.0
                2016-11-18 9414.0     3217   137025.0
     2016-11-18 1970-01-01 2405.0       68     1015.0
                2016-11-18 2405.0     1226    73080.0
1016 2016-11-19 1970-01-01 3372.0       18     3048.0
1020 2016-11-21 1970-01-01 7412.0       69     2040.0
1021 2016-11-22 1970-01-01 8023.0       68     1021.0
1022 2016-11-23 1970-01-01 7870.0      136     2044.0
1024 2016-11-25 1970-01-01 6944.0        6     1024.0
1025 2016-11-26 1970-01-01 10768.0     204     3075.0
1026 2016-11-27 1970-01-01 9679.0       68     1026.0
1027 2016-11-28 1970-01-01 6219.0        6     1027.0
     2016-11-29 1970-01-01 1783.0       36     2054.0

[346 rows x 2 columns]

In [93]:
result.reset_index(inplace=True)

In [66]:
result

      sid       date     PayTime   acid_y   Money      sid_r
0    1001 2016-11-10  1970-01-01  12353.0      75     3003.0
1    1001 2016-11-10  2016-11-10  12353.0  123312  3629626.0
2    1001 2016-11-10  2016-11-11  12353.0   48985  1092091.0
3    1001 2016-11-10  2016-11-12  12353.0   22693   592592.0
4    1001 2016-11-10  2016-11-13  12353.0   20406   447447.0
5    1001 2016-11-10  2016-11-14  12353.0    6595   282282.0
6    1001 2016-11-10  2016-11-15  12353.0    8432   223223.0
7    1001 2016-11-10  2016-11-16  12353.0    6989   158158.0
8    1001 2016-11-10  2016-11-17  12353.0    2042   115115.0
9    1001 2016-11-10  2016-11-18  12353.0     522    59059.0
10   1001 2016-11-11  2016-11-11   2088.0    2941   188188.0
11   1001 2016-11-11  2016-11-12   2088.0    2802    98098.0
12   1001 2016-11-11  2016-11-13   2088.0     831    30030.0
13   1001 2016-11-11  2016-11-14   2088.0     438    17017.0
14   1001 2016-11-11  2016-11-15   2088.0     666    15015.0
15   1001 2016-11-11  2016-11-16   2088.0      14     4004.0
16   1001 2016-11-11  2016-11-17   2088.0     135     9009.0
17   1001 2016-11-12  1970-01-01   2169.0       2     2002.0
18   1001 2016-11-12  2016-11-12   2169.0    6764   114114.0
19   1001 2016-11-12  2016-11-13   2169.0    1282    54054.0
20   1001 2016-11-12  2016-11-14   2169.0     663    25025.0
21   1001 2016-11-12  2016-11-15   2169.0     647    24024.0
22   1001 2016-11-12  2016-11-16   2169.0     215    16016.0
23   1001 2016-11-12  2016-11-17   2169.0     332    15015.0
24   1001 2016-11-12  2016-11-18   2169.0      80     3003.0
25   1001 2016-11-13  2016-11-13   1394.0    1122    59059.0
26   1001 2016-11-13  2016-11-14   1394.0    1023    64064.0
27   1001 2016-11-13  2016-11-15   1394.0     543    26026.0
28   1001 2016-11-13  2016-11-16   1394.0     318    14014.0
29   1001 2016-11-13  2016-11-17   1394.0      67     4004.0
..    ...        ...         ...      ...     ...        ...
316  1013 2016-11-15  2016-11-16  12914.0   55990   882323.0
317  1013 2016-11-15  2016-11-17  12914.0   16209   404187.0
318  1013 2016-11-15  2016-11-18  12914.0    1982    54702.0
319  1013 2016-11-16  1970-01-01   3258.0     205     4052.0
320  1013 2016-11-16  2016-11-16   3258.0    9304   450785.0
321  1013 2016-11-16  2016-11-17   3258.0    4974   133716.0
322  1013 2016-11-16  2016-11-18   3258.0     381    15195.0
323  1013 2016-11-17  2016-11-17     61.0     648     1013.0
324  1013 2016-11-17  2016-11-18     61.0      99     3039.0
325  1014 2016-11-16  1970-01-01  10668.0      90    18252.0
326  1014 2016-11-16  2016-11-16  10668.0   53705  1302990.0
327  1014 2016-11-16  2016-11-17  10668.0   24937   750360.0
328  1014 2016-11-16  2016-11-18  10668.0    3147    82134.0
329  1014 2016-11-17  1970-01-01   2968.0       1     1014.0
330  1014 2016-11-17  2016-11-17   2968.0   10651   350844.0
331  1014 2016-11-17  2016-11-18   2968.0     659    27378.0
332  1015 2016-11-17  1970-01-01   9414.0     136     2030.0
333  1015 2016-11-17  2016-11-17   9414.0   77134  1126650.0
334  1015 2016-11-17  2016-11-18   9414.0    3217   137025.0
335  1015 2016-11-18  1970-01-01   2405.0      68     1015.0
336  1015 2016-11-18  2016-11-18   2405.0    1226    73080.0
337  1016 2016-11-19  1970-01-01   3372.0      18     3048.0
338  1020 2016-11-21  1970-01-01   7412.0      69     2040.0
339  1021 2016-11-22  1970-01-01   8023.0      68     1021.0
340  1022 2016-11-23  1970-01-01   7870.0     136     2044.0
341  1024 2016-11-25  1970-01-01   6944.0       6     1024.0
342  1025 2016-11-26  1970-01-01  10768.0     204     3075.0
343  1026 2016-11-27  1970-01-01   9679.0      68     1026.0
344  1027 2016-11-28  1970-01-01   6219.0       6     1027.0
345  1027 2016-11-29  1970-01-01   1783.0      36     2054.0

[346 rows x 6 columns]

In [67]:
result['consume'] = result.Money/result.acid_y

In [90]:
result['day'] = (result['PayTime'].apply(lambda x:datetime.date(int(str(x).split('-')[0]),int(str(x).split('-')[1]),int(str(x).split('-')[2])))-result['date'].apply(lambda x:x.date()))

In [92]:
result[['sid','date','consume','day']]

      sid       date    consume         day
0    1001 2016-11-10   0.006071 -17115 days
1    1001 2016-11-10   9.982352      0 days
2    1001 2016-11-10   3.965433      1 days
3    1001 2016-11-10   1.837044      2 days
4    1001 2016-11-10   1.651906      3 days
5    1001 2016-11-10   0.533878      4 days
6    1001 2016-11-10   0.682587      5 days
7    1001 2016-11-10   0.565773      6 days
8    1001 2016-11-10   0.165304      7 days
9    1001 2016-11-10   0.042257      8 days
10   1001 2016-11-11   1.408525      0 days
11   1001 2016-11-11   1.341954      1 days
12   1001 2016-11-11   0.397989      2 days
13   1001 2016-11-11   0.209770      3 days
14   1001 2016-11-11   0.318966      4 days
15   1001 2016-11-11   0.006705      5 days
16   1001 2016-11-11   0.064655      6 days
17   1001 2016-11-12   0.000922 -17117 days
18   1001 2016-11-12   3.118488      0 days
19   1001 2016-11-12   0.591056      1 days
20   1001 2016-11-12   0.305671      2 days
21   1001 2016-11-12   0.298294      3 days
22   1001 2016-11-12   0.099124      4 days
23   1001 2016-11-12   0.153066      5 days
24   1001 2016-11-12   0.036883      6 days
25   1001 2016-11-13   0.804878      0 days
26   1001 2016-11-13   0.733859      1 days
27   1001 2016-11-13   0.389527      2 days
28   1001 2016-11-13   0.228121      3 days
29   1001 2016-11-13   0.048063      4 days
..    ...        ...        ...         ...
316  1013 2016-11-15   4.335605      1 days
317  1013 2016-11-15   1.255149      2 days
318  1013 2016-11-15   0.153477      3 days
319  1013 2016-11-16   0.062922 -17121 days
320  1013 2016-11-16   2.855740      0 days
321  1013 2016-11-16   1.526703      1 days
322  1013 2016-11-16   0.116943      2 days
323  1013 2016-11-17  10.622951      0 days
324  1013 2016-11-17   1.622951      1 days
325  1014 2016-11-16   0.008436 -17121 days
326  1014 2016-11-16   5.034214      0 days
327  1014 2016-11-16   2.337552      1 days
328  1014 2016-11-16   0.294994      2 days
329  1014 2016-11-17   0.000337 -17122 days
330  1014 2016-11-17   3.588612      0 days
331  1014 2016-11-17   0.222035      1 days
332  1015 2016-11-17   0.014447 -17122 days
333  1015 2016-11-17   8.193542      0 days
334  1015 2016-11-17   0.341725      1 days
335  1015 2016-11-18   0.028274 -17123 days
336  1015 2016-11-18   0.509771      0 days
337  1016 2016-11-19   0.005338 -17124 days
338  1020 2016-11-21   0.009309 -17126 days
339  1021 2016-11-22   0.008476 -17127 days
340  1022 2016-11-23   0.017281 -17128 days
341  1024 2016-11-25   0.000864 -17130 days
342  1025 2016-11-26   0.018945 -17131 days
343  1026 2016-11-27   0.007026 -17132 days
344  1027 2016-11-28   0.000965 -17133 days
345  1027 2016-11-29   0.020191 -17134 days

[346 rows x 4 columns]

In [136]:
# -*- coding:utf-8 -*-
import pandas as pd
import codecs
import json
import io
import StringIO
from pandas.io.json import json_normalize
import datetime

if __name__ == '__main__':
    with open('/Users/tq/Downloads/logics_pay.10.11.2016.log', 'r') as json_data:
        json_buffer = StringIO.StringIO()
        for line in json_data:
            tempMap = {}
            json_dicts = json.loads(line)  # 读取json数据为list[dict]结构
            tempMap.setdefault('sid', json_dicts['sid'])
            tempMap.setdefault('acid', json_dicts['accountid'])
            tempMap.setdefault('Money', json_dicts['info']['Money'])
            tempMap.setdefault('PayTime', json_dicts['utc8'][0:10])
            json_temp = json.dumps(tempMap)
            json_buffer.writelines(json_temp + "\n")

    pay = pd.read_json(json_buffer.getvalue(), lines=True)
    acidBysid = pd.read_json('/Users/tq/Downloads/acid_creatTime.json')
    acid_temp = acidBysid[['acid', 'date', 'sid']]
    creatGroup = acid_temp.groupby([acid_temp['date'], acid_temp['sid']]).count()
    creatGroup.rename(columns={'acid': 'peopleCount'}, inplace=True)
    creatGroup.reset_index(inplace=True)
    #print creatGroup

    payMerge = pay.merge(acid_temp, left_on='acid', right_on='acid', how='left',suffixes=['', '_r'])
    # print "####"
    # print payMerge

In [138]:
    creatGroup

          date   sid  peopleCount
0   2016-11-10  1001        12353
1   2016-11-10  1002        12406
2   2016-11-10  1003        17578
3   2016-11-10  1004        18604
4   2016-11-10  2001         3079
5   2016-11-10  3001        10208
6   2016-11-10  3002        13935
7   2016-11-11  1001         2088
8   2016-11-11  1002         1738
9   2016-11-11  1003          310
10  2016-11-11  1004         5103
11  2016-11-11  1005        10764
12  2016-11-11  1006        13456
13  2016-11-11  2001         3732
14  2016-11-11  2002        11806
15  2016-11-11  2003         6563
16  2016-11-11  3001         1115
17  2016-11-11  3002         3693
18  2016-11-11  3003        11645
19  2016-11-12  1001         2169
20  2016-11-12  1002          263
21  2016-11-12  1003          173
22  2016-11-12  1004          342
23  2016-11-12  1005          244
24  2016-11-12  1006         6723
25  2016-11-12  1007        11331
26  2016-11-12  1008        11722
27  2016-11-12  1009         4850
28  2016-11-12  2001         1515
29  2016-11-12  2002          308
..         ...   ...          ...
831 2016-12-01  1026            6
832 2016-12-01  1027            5
833 2016-12-01  1028            4
834 2016-12-01  1029          832
835 2016-12-01  2001            3
836 2016-12-01  2008            1
837 2016-12-01  2009            1
838 2016-12-01  2011            1
839 2016-12-01  2012           73
840 2016-12-01  3001           60
841 2016-12-01  3002            8
842 2016-12-01  3003            4
843 2016-12-01  3004            3
844 2016-12-01  3005            7
845 2016-12-01  3007            4
846 2016-12-01  3008            3
847 2016-12-01  3009            9
848 2016-12-01  3010           29
849 2016-12-01  3011            4
850 2016-12-01  3012           13
851 2016-12-01  3013            6
852 2016-12-01  3014            3
853 2016-12-01  3015            1
854 2016-12-01  3016            1
855 2016-12-01  3017            5
856 2016-12-01  3018            3
857 2016-12-01  3019            7
858 2016-12-01  3020           16
859 2016-12-01  3021           34
860 2016-12-01  3022         1332

[861 rows x 3 columns]

In [139]:
    payMerge

,Money,PayTime,acid,sid,date,sid_r
0,1,2016-11-11,200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21,1001,2016-11-11,1001.0
1,6,2016-11-15,200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55,1013,2016-11-15,1013.0
2,6,2016-11-15,200:1009:1337f849-a408-4a05-bcde-d941315d0ba1,1009,2016-11-12,1009.0
3,25,2016-11-11,200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd,1003,2016-11-10,1003.0
4,328,2016-11-12,200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676,1005,2016-11-11,1005.0
5,30,2016-11-11,200:1001:58a95093-15d6-4261-9151-b6dd03029f3e,1001,2016-11-10,1001.0
6,98,2016-11-13,200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87,1009,2016-11-13,1009.0
7,6,2016-11-13,200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220,1001,2016-11-10,1001.0
8,6,2016-11-15,200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953,1012,2016-11-14,1012.0
9,6,2016-11-15,200:1004:82143338-3495-46b0-b00d-fe84a7c94225,1004,2016-11-11,1004.0
10,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0
11,1,2016-11-12,200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e,1002,2016-11-10,1002.0
12,6,2016-11-12,200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9,1001,2016-11-10,1001.0
13,98,2016-11-14,200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b,1003,2016-11-10,1003.0
14,68,2016-11-18,200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,1015,2016-11-17,1015.0
15,30,2016-11-13,200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,1006,2016-11-12,1006.0
16,6,2016-11-17,200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,1005,2016-11-11,1005.0
17,68,2016-11-10,200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268,1001,2016-11-10,1001.0
18,30,2016-11-12,200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be,1002,2016-11-12,1002.0
19,6,2016-11-11,200:1001:3039ef63-1524-46cf-ba49-9188aa081002,1001,2016-11-10,1001.0
20,648,2016-11-10,200:1004:87614525-f38c-43ce-a153-60ef0e2f1578,1004,2016-11-10,1004.0
21,25,2016-11-11,200:1001:0d39521a-4a45-480c-8772-7c24225c6c48,1001,2016-11-10,1001.0
22,6,2016-11-11,200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b,1002,2016-11-10,1002.0
23,6,2016-11-10,200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b,1001,2016-11-10,1001.0
24,1,2016-11-12,200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97,1003,2016-11-10,1003.0
25,6,2016-11-10,200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027,1001,2016-11-10,1001.0
26,6,2016-11-13,200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3,1006,2016-11-11,1006.0
27,6,2016-11-12,200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3,1004,2016-11-10,1004.0
28,6,2016-11-10,200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153,1001,2016-11-10,1001.0
29,25,2016-11-14,200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee,1011,2016-11-14,1011.0
...,...,...,...,...,...,...
57660,6,2016-11-18,200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98,1005,2016-11-11,1005.0
57661,1,2016-11-13,200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7,1002,2016-11-10,1002.0
57662,30,2016-11-13,200:1009:806567a1-8565-423f-8e04-42cf1b4dade6,1009,2016-11-12,1009.0
57663,68,2016-11-16,200:1013:85db0143-369d-4351-8698-4842eb50534f,1013,2016-11-15,1013.0
57664,6,1970-01-01,200:1010:aafe8ff2-029d-4a77-b395-af0de514df88,1010,2016-11-13,1010.0
57665,30,2016-11-14,200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,1012,2016-11-14,1012.0
57666,6,2016-11-10,200:1003:32c155c7-050a-440b-968a-a5000e6add3c,1003,2016-11-10,1003.0
57667,1,2016-11-10,200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b,1001,2016-11-10,1001.0
57668,25,2016-11-13,200:1011:1369c61f-b375-4bf8-bb11-b9220301362e,1011,2016-11-13,1011.0
57669,6,2016-11-11,200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,1004,2016-11-10,1004.0
57670,68,2016-11-14,200:1011:714f9a06-decc-402b-8e49-3205bf97ba31,1011,2016-11-13,1011.0
57671,25,2016-11-16,200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea,1003,2016-11-10,1003.0
57672,68,2016-11-12,200:1002:95940643-2054-48db-b352-25060ddf191e,1002,2016-11-10,1002.0
57673,6,2016-11-13,200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702,1009,2016-11-13,1009.0
57674,30,2016-11-12,200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d,1007,2016-11-12,1007.0
57675,6,2016-11-13,200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a,1010,2016-11-13,1010.0
57676,6,2016-11-15,200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40,1011,2016-11-13,1011.0
57677,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0
57678,30,2016-11-15,200:1004:36f79246-bb89-483a-be3b-630c6f4e1032,1004,2016-11-10,1004.0
57679,68,2016-11-13,200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,1008,2016-11-12,1008.0
57680,6,2016-11-14,200:1004:17926a73-59eb-4467-89f1-9e9978a019dc,1004,2016-11-11,1004.0
57681,30,2016-11-13,200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e,1008,2016-11-12,1008.0
57682,30,2016-11-17,200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea,1013,2016-11-15,1013.0
57683,1,2016-11-12,200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724,1006,2016-11-11,1006.0
57684,1,2016-11-11,200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598,1005,2016-11-11,1005.0
57685,6,2016-11-15,200:1006:0875ee8b-2319-4458-b85a-031760c5535f,1006,2016-11-12,1006.0
57686,6,2016-11-17,200:1011:312fda94-6cfc-4299-9b63-6964df5b224a,1011,2016-11-13,1011.0
57687,30,2016-11-17,200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333,1015,2016-11-17,1015.0
57688,1,2016-11-10,200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,1001,2016-11-10,1001.0
57689,1,2016-11-13,200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,1009,2016-11-12,1009.0

In [140]:
    finalpayMerge = pd.merge(payMerge, creatGroup, on=['date', 'sid'], how='left', suffixes=['', '_r'])

In [141]:
    finalpayMerge

,Money,PayTime,acid,sid,date,sid_r,peopleCount
0,1,2016-11-11,200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21,1001,2016-11-11,1001.0,2088.0
1,6,2016-11-15,200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55,1013,2016-11-15,1013.0,12914.0
2,6,2016-11-15,200:1009:1337f849-a408-4a05-bcde-d941315d0ba1,1009,2016-11-12,1009.0,4850.0
3,25,2016-11-11,200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd,1003,2016-11-10,1003.0,17578.0
4,328,2016-11-12,200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676,1005,2016-11-11,1005.0,10764.0
5,30,2016-11-11,200:1001:58a95093-15d6-4261-9151-b6dd03029f3e,1001,2016-11-10,1001.0,12353.0
6,98,2016-11-13,200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87,1009,2016-11-13,1009.0,6877.0
7,6,2016-11-13,200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220,1001,2016-11-10,1001.0,12353.0
8,6,2016-11-15,200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953,1012,2016-11-14,1012.0,10656.0
9,6,2016-11-15,200:1004:82143338-3495-46b0-b00d-fe84a7c94225,1004,2016-11-11,1004.0,5103.0
10,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0,11970.0
11,1,2016-11-12,200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e,1002,2016-11-10,1002.0,12406.0
12,6,2016-11-12,200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9,1001,2016-11-10,1001.0,12353.0
13,98,2016-11-14,200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b,1003,2016-11-10,1003.0,17578.0
14,68,2016-11-18,200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,1015,2016-11-17,1015.0,9414.0
15,30,2016-11-13,200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,1006,2016-11-12,1006.0,6723.0
16,6,2016-11-17,200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,1005,2016-11-11,1005.0,10764.0
17,68,2016-11-10,200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268,1001,2016-11-10,1001.0,12353.0
18,30,2016-11-12,200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be,1002,2016-11-12,1002.0,263.0
19,6,2016-11-11,200:1001:3039ef63-1524-46cf-ba49-9188aa081002,1001,2016-11-10,1001.0,12353.0
20,648,2016-11-10,200:1004:87614525-f38c-43ce-a153-60ef0e2f1578,1004,2016-11-10,1004.0,18604.0
21,25,2016-11-11,200:1001:0d39521a-4a45-480c-8772-7c24225c6c48,1001,2016-11-10,1001.0,12353.0
22,6,2016-11-11,200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b,1002,2016-11-10,1002.0,12406.0
23,6,2016-11-10,200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b,1001,2016-11-10,1001.0,12353.0
24,1,2016-11-12,200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97,1003,2016-11-10,1003.0,17578.0
25,6,2016-11-10,200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027,1001,2016-11-10,1001.0,12353.0
26,6,2016-11-13,200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3,1006,2016-11-11,1006.0,13456.0
27,6,2016-11-12,200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3,1004,2016-11-10,1004.0,18604.0
28,6,2016-11-10,200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153,1001,2016-11-10,1001.0,12353.0
29,25,2016-11-14,200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee,1011,2016-11-14,1011.0,7061.0
...,...,...,...,...,...,...,...
57660,6,2016-11-18,200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98,1005,2016-11-11,1005.0,10764.0
57661,1,2016-11-13,200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7,1002,2016-11-10,1002.0,12406.0
57662,30,2016-11-13,200:1009:806567a1-8565-423f-8e04-42cf1b4dade6,1009,2016-11-12,1009.0,4850.0
57663,68,2016-11-16,200:1013:85db0143-369d-4351-8698-4842eb50534f,1013,2016-11-15,1013.0,12914.0
57664,6,1970-01-01,200:1010:aafe8ff2-029d-4a77-b395-af0de514df88,1010,2016-11-13,1010.0,11970.0
57665,30,2016-11-14,200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,1012,2016-11-14,1012.0,10656.0
57666,6,2016-11-10,200:1003:32c155c7-050a-440b-968a-a5000e6add3c,1003,2016-11-10,1003.0,17578.0
57667,1,2016-11-10,200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b,1001,2016-11-10,1001.0,12353.0
57668,25,2016-11-13,200:1011:1369c61f-b375-4bf8-bb11-b9220301362e,1011,2016-11-13,1011.0,5927.0
57669,6,2016-11-11,200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,1004,2016-11-10,1004.0,18604.0
57670,68,2016-11-14,200:1011:714f9a06-decc-402b-8e49-3205bf97ba31,1011,2016-11-13,1011.0,5927.0
57671,25,2016-11-16,200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea,1003,2016-11-10,1003.0,17578.0
57672,68,2016-11-12,200:1002:95940643-2054-48db-b352-25060ddf191e,1002,2016-11-10,1002.0,12406.0
57673,6,2016-11-13,200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702,1009,2016-11-13,1009.0,6877.0
57674,30,2016-11-12,200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d,1007,2016-11-12,1007.0,11331.0
57675,6,2016-11-13,200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a,1010,2016-11-13,1010.0,11970.0
57676,6,2016-11-15,200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40,1011,2016-11-13,1011.0,5927.0
57677,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0,11970.0
57678,30,2016-11-15,200:1004:36f79246-bb89-483a-be3b-630c6f4e1032,1004,2016-11-10,1004.0,18604.0
57679,68,2016-11-13,200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,1008,2016-11-12,1008.0,11722.0
57680,6,2016-11-14,200:1004:17926a73-59eb-4467-89f1-9e9978a019dc,1004,2016-11-11,1004.0,5103.0
57681,30,2016-11-13,200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e,1008,2016-11-12,1008.0,11722.0
57682,30,2016-11-17,200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea,1013,2016-11-15,1013.0,12914.0
57683,1,2016-11-12,200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724,1006,2016-11-11,1006.0,13456.0
57684,1,2016-11-11,200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598,1005,2016-11-11,1005.0,10764.0
57685,6,2016-11-15,200:1006:0875ee8b-2319-4458-b85a-031760c5535f,1006,2016-11-12,1006.0,6723.0
57686,6,2016-11-17,200:1011:312fda94-6cfc-4299-9b63-6964df5b224a,1011,2016-11-13,1011.0,5927.0
57687,30,2016-11-17,200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333,1015,2016-11-17,1015.0,9414.0
57688,1,2016-11-10,200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,1001,2016-11-10,1001.0,12353.0
57689,1,2016-11-13,200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,1009,2016-11-12,1009.0,4850.0

In [279]:
    data2 = payMerge.reset_index()
    data3 = data2.set_index(["sid", "date", "PayTime"])   # index is the new column created by reset_index
    running_sum = data3.groupby(level=[0,1,2]).sum().groupby(level=[0,1]).cumsum() 
    result = payMerge.groupby([payMerge['sid'], payMerge['date'], payMerge['PayTime']]).sum()

In [281]:
    data2

,index,Money,PayTime,acid,sid,date,sid_r
0,0,1,2016-11-11,200:1001:2f4e9362-1d87-48df-ba35-011f278a8a21,1001,2016-11-11,1001.0
1,1,6,2016-11-15,200:1013:99ca640f-1c2f-4e6a-b57c-2fd107139d55,1013,2016-11-15,1013.0
2,2,6,2016-11-15,200:1009:1337f849-a408-4a05-bcde-d941315d0ba1,1009,2016-11-12,1009.0
3,3,25,2016-11-11,200:1003:4ef0daaf-a6cd-433f-8937-a520ebd07acd,1003,2016-11-10,1003.0
4,4,328,2016-11-12,200:1005:a60aa1e3-8042-4764-b510-46fdd0d73676,1005,2016-11-11,1005.0
5,5,30,2016-11-11,200:1001:58a95093-15d6-4261-9151-b6dd03029f3e,1001,2016-11-10,1001.0
6,6,98,2016-11-13,200:1009:14ebc642-bbfd-4a0a-b56a-9de573c23c87,1009,2016-11-13,1009.0
7,7,6,2016-11-13,200:1001:92e31e79-2cdc-43c9-9fad-ce7ec6fae220,1001,2016-11-10,1001.0
8,8,6,2016-11-15,200:1012:772fc1c4-a142-4bfc-afcf-750b64cef953,1012,2016-11-14,1012.0
9,9,6,2016-11-15,200:1004:82143338-3495-46b0-b00d-fe84a7c94225,1004,2016-11-11,1004.0
10,10,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0
11,11,1,2016-11-12,200:1002:f78a801b-4be8-4a19-a8cd-d45072c54c3e,1002,2016-11-10,1002.0
12,12,6,2016-11-12,200:1001:6189a20a-343f-4ec0-a57c-e471c6afe5f9,1001,2016-11-10,1001.0
13,13,98,2016-11-14,200:1003:11b12fa4-41f8-4501-ad5a-9a4c863e414b,1003,2016-11-10,1003.0
14,14,68,2016-11-18,200:1015:dfd48ca8-c206-43c7-bb3e-a65c5512ebc2,1015,2016-11-17,1015.0
15,15,30,2016-11-13,200:1006:2bbf8a15-67fb-4dd7-beb8-519bf3ffda16,1006,2016-11-12,1006.0
16,16,6,2016-11-17,200:1005:e8d06097-b6bc-4c07-b605-a16c5e8ee6c9,1005,2016-11-11,1005.0
17,17,68,2016-11-10,200:1001:d7479b16-a64b-4aac-83ab-bd9128d35268,1001,2016-11-10,1001.0
18,18,30,2016-11-12,200:1002:f937bef6-41aa-48cc-8638-c6866e6ad8be,1002,2016-11-12,1002.0
19,19,6,2016-11-11,200:1001:3039ef63-1524-46cf-ba49-9188aa081002,1001,2016-11-10,1001.0
20,20,648,2016-11-10,200:1004:87614525-f38c-43ce-a153-60ef0e2f1578,1004,2016-11-10,1004.0
21,21,25,2016-11-11,200:1001:0d39521a-4a45-480c-8772-7c24225c6c48,1001,2016-11-10,1001.0
22,22,6,2016-11-11,200:1002:20cd29e1-1d00-4429-b85e-44ab5cdafa3b,1002,2016-11-10,1002.0
23,23,6,2016-11-10,200:1001:ba6e64ec-97bd-45e7-ab04-a3023688971b,1001,2016-11-10,1001.0
24,24,1,2016-11-12,200:1003:d9dcca4e-3aa0-41a0-a586-6ac071976b97,1003,2016-11-10,1003.0
25,25,6,2016-11-10,200:1001:b1fcb7b5-a7ae-495f-b53b-7d36f557f027,1001,2016-11-10,1001.0
26,26,6,2016-11-13,200:1006:f23121c7-4324-4a75-87f8-3a89ae8eb4a3,1006,2016-11-11,1006.0
27,27,6,2016-11-12,200:1004:524dacd8-fcd1-41f4-9111-b6372a1635e3,1004,2016-11-10,1004.0
28,28,6,2016-11-10,200:1001:0d464ea9-3a72-4e24-8637-e409a7b67153,1001,2016-11-10,1001.0
29,29,25,2016-11-14,200:1011:413c5fbc-922b-428f-8bb7-b23085f3a3ee,1011,2016-11-14,1011.0
...,...,...,...,...,...,...,...
57660,57660,6,2016-11-18,200:1005:c81b59f3-4fcd-48fc-8feb-708e4703ae98,1005,2016-11-11,1005.0
57661,57661,1,2016-11-13,200:1002:844a0b58-2c0e-460a-a777-16f4a1d0f1b7,1002,2016-11-10,1002.0
57662,57662,30,2016-11-13,200:1009:806567a1-8565-423f-8e04-42cf1b4dade6,1009,2016-11-12,1009.0
57663,57663,68,2016-11-16,200:1013:85db0143-369d-4351-8698-4842eb50534f,1013,2016-11-15,1013.0
57664,57664,6,1970-01-01,200:1010:aafe8ff2-029d-4a77-b395-af0de514df88,1010,2016-11-13,1010.0
57665,57665,30,2016-11-14,200:1012:9bb36b5a-97cc-4ad7-8a25-1e2272281a5b,1012,2016-11-14,1012.0
57666,57666,6,2016-11-10,200:1003:32c155c7-050a-440b-968a-a5000e6add3c,1003,2016-11-10,1003.0
57667,57667,1,2016-11-10,200:1001:ee8b742e-47e7-4da7-acbe-3e981de4322b,1001,2016-11-10,1001.0
57668,57668,25,2016-11-13,200:1011:1369c61f-b375-4bf8-bb11-b9220301362e,1011,2016-11-13,1011.0
57669,57669,6,2016-11-11,200:1004:a057ccc6-7e84-4a4b-9bca-e2a383ed9c7f,1004,2016-11-10,1004.0
57670,57670,68,2016-11-14,200:1011:714f9a06-decc-402b-8e49-3205bf97ba31,1011,2016-11-13,1011.0
57671,57671,25,2016-11-16,200:1003:64c0cc4b-7dd6-4de6-8075-27954b629dea,1003,2016-11-10,1003.0
57672,57672,68,2016-11-12,200:1002:95940643-2054-48db-b352-25060ddf191e,1002,2016-11-10,1002.0
57673,57673,6,2016-11-13,200:1009:880fd636-cc7e-4ce2-8840-73dcca43a702,1009,2016-11-13,1009.0
57674,57674,30,2016-11-12,200:1007:6a4f7847-50bd-43b9-bfa6-c8445413503d,1007,2016-11-12,1007.0
57675,57675,6,2016-11-13,200:1010:8a9ea03e-2045-4f2d-a987-548c8299e57a,1010,2016-11-13,1010.0
57676,57676,6,2016-11-15,200:1011:ab861363-a5b5-40f8-8b51-559c6797eb40,1011,2016-11-13,1011.0
57677,57677,1,2016-11-14,200:1010:e5699789-ce13-47ec-aba5-1a4b2aedfcff,1010,2016-11-13,1010.0
57678,57678,30,2016-11-15,200:1004:36f79246-bb89-483a-be3b-630c6f4e1032,1004,2016-11-10,1004.0
57679,57679,68,2016-11-13,200:1008:7b60f98e-a80c-4ffb-8c84-1a9b1bf6c850,1008,2016-11-12,1008.0
57680,57680,6,2016-11-14,200:1004:17926a73-59eb-4467-89f1-9e9978a019dc,1004,2016-11-11,1004.0
57681,57681,30,2016-11-13,200:1008:7541a26e-10d7-4bbc-9b5f-a480e766c05e,1008,2016-11-12,1008.0
57682,57682,30,2016-11-17,200:1013:205ec6d1-d46e-42ea-a9f0-908017ef57ea,1013,2016-11-15,1013.0
57683,57683,1,2016-11-12,200:1006:93c29e25-8623-4004-bd50-cf6cbfe81724,1006,2016-11-11,1006.0
57684,57684,1,2016-11-11,200:1005:6f69a8ba-afea-464e-b72a-1c9ee9057598,1005,2016-11-11,1005.0
57685,57685,6,2016-11-15,200:1006:0875ee8b-2319-4458-b85a-031760c5535f,1006,2016-11-12,1006.0
57686,57686,6,2016-11-17,200:1011:312fda94-6cfc-4299-9b63-6964df5b224a,1011,2016-11-13,1011.0
57687,57687,30,2016-11-17,200:1015:aafffa5b-ba19-4c40-b85a-64e0f3979333,1015,2016-11-17,1015.0
57688,57688,1,2016-11-10,200:1001:9f9f36ab-79f0-4bd9-8cb2-4a767acb6fb7,1001,2016-11-10,1001.0
57689,57689,1,2016-11-13,200:1009:aa81f47d-99bc-4c68-a31e-ff9c1e21f1df,1009,2016-11-12,1009.0

In [280]:
    running_sum

                             Money      index      sid_r
sid  date       PayTime
1001 2016-11-10 1970-01-01      75      31683     3003.0
                2016-11-10  123387  103928365  3632629.0
                2016-11-11  172372  135390253  4724720.0
                2016-11-12  195065  152231909  5317312.0
                2016-11-13  215471  164738394  5764759.0
                2016-11-14  222066  172776796  6047041.0
                2016-11-15  230498  179281116  6270264.0
                2016-11-16  237487  183886212  6428422.0
                2016-11-17  239529  186941413  6543537.0
                2016-11-18  240051  188926054  6602596.0
     2016-11-11 2016-11-11    2941    5221922   188188.0
                2016-11-12    5743    8161267   286286.0
                2016-11-13    6574    9110894   316316.0
                2016-11-14    7012    9610239   333333.0
                2016-11-15    7678   10082094   348348.0
                2016-11-16    7692   10236583   352352.0
                2016-11-17    7827   10569656   361361.0
     2016-11-12 1970-01-01       2      51098     2002.0
                2016-11-12    6766    3159823   116116.0
                2016-11-13    8048    4754190   170170.0
                2016-11-14    8711    5466175   195195.0
                2016-11-15    9358    6182968   219219.0
                2016-11-16    9573    6651274   235235.0
                2016-11-17    9905    7049122   250250.0
                2016-11-18    9985    7146335   253253.0
     2016-11-13 2016-11-13    1122    1548095    59059.0
                2016-11-14    2145    3402705   123123.0
                2016-11-15    2688    4133596   149149.0
                2016-11-16    3006    4593108   163163.0
                2016-11-17    3073    4676227   167167.0
...                            ...        ...        ...
1013 2016-11-15 2016-11-16  113589   65515931  2334965.0
                2016-11-17  129798   77315322  2739152.0
                2016-11-18  131780   78688183  2793854.0
     2016-11-16 1970-01-01     205     119751     4052.0
                2016-11-16    9509   13609688   454837.0
                2016-11-17   14483   17611766   588553.0
                2016-11-18   14864   18019943   603748.0
     2016-11-17 2016-11-17     648      51193     1013.0
                2016-11-18     747     159470     4052.0
1014 2016-11-16 1970-01-01      90     491221    18252.0
                2016-11-16   53795   37425504  1321242.0
                2016-11-17   78732   58707021  2071602.0
                2016-11-18   81879   61387814  2153736.0
     2016-11-17 1970-01-01       1      48582     1014.0
                2016-11-17   10652   10308202   351858.0
                2016-11-18   11311   11128042   379236.0
1015 2016-11-17 1970-01-01     136      45156     2030.0
                2016-11-17   77270   31568981  1128680.0
                2016-11-18   80487   35715730  1265705.0
     2016-11-18 1970-01-01      68      15770     1015.0
                2016-11-18    1294    2223382    74095.0
1016 2016-11-19 1970-01-01      18      66352     3048.0
1020 2016-11-21 1970-01-01      69      35528     2040.0
1021 2016-11-22 1970-01-01      68      12743     1021.0
1022 2016-11-23 1970-01-01     136      60949     2044.0
1024 2016-11-25 1970-01-01       6      37657     1024.0
1025 2016-11-26 1970-01-01     204      70487     3075.0
1026 2016-11-27 1970-01-01      68       3031     1026.0
1027 2016-11-28 1970-01-01       6      29675     1027.0
     2016-11-29 1970-01-01      36      89164     2054.0

[346 rows x 3 columns]

In [209]:
    del result['sid_r']

In [230]:
    result

                                         Money
sid  date       PayTime    peopleCount
1001 2016-11-10 1970-01-01 12353.0          75
                2016-11-10 12353.0      123312
                2016-11-11 12353.0       48985
                2016-11-12 12353.0       22693
                2016-11-13 12353.0       20406
                2016-11-14 12353.0        6595
                2016-11-15 12353.0        8432
                2016-11-16 12353.0        6989
                2016-11-17 12353.0        2042
                2016-11-18 12353.0         522
     2016-11-11 2016-11-11 2088.0         2941
                2016-11-12 2088.0         2802
                2016-11-13 2088.0          831
                2016-11-14 2088.0          438
                2016-11-15 2088.0          666
                2016-11-16 2088.0           14
                2016-11-17 2088.0          135
     2016-11-12 1970-01-01 2169.0            2
                2016-11-12 2169.0         6764
                2016-11-13 2169.0         1282
                2016-11-14 2169.0          663
                2016-11-15 2169.0          647
                2016-11-16 2169.0          215
                2016-11-17 2169.0          332
                2016-11-18 2169.0           80
     2016-11-13 2016-11-13 1394.0         1122
                2016-11-14 1394.0         1023
                2016-11-15 1394.0          543
                2016-11-16 1394.0          318
                2016-11-17 1394.0           67
...                                        ...
1013 2016-11-15 2016-11-16 12914.0       55990
                2016-11-17 12914.0       16209
                2016-11-18 12914.0        1982
     2016-11-16 1970-01-01 3258.0          205
                2016-11-16 3258.0         9304
                2016-11-17 3258.0         4974
                2016-11-18 3258.0          381
     2016-11-17 2016-11-17 61.0            648
                2016-11-18 61.0             99
1014 2016-11-16 1970-01-01 10668.0          90
                2016-11-16 10668.0       53705
                2016-11-17 10668.0       24937
                2016-11-18 10668.0        3147
     2016-11-17 1970-01-01 2968.0            1
                2016-11-17 2968.0        10651
                2016-11-18 2968.0          659
1015 2016-11-17 1970-01-01 9414.0          136
                2016-11-17 9414.0        77134
                2016-11-18 9414.0         3217
     2016-11-18 1970-01-01 2405.0           68
                2016-11-18 2405.0         1226
1016 2016-11-19 1970-01-01 3372.0           18
1020 2016-11-21 1970-01-01 7412.0           69
1021 2016-11-22 1970-01-01 8023.0           68
1022 2016-11-23 1970-01-01 7870.0          136
1024 2016-11-25 1970-01-01 6944.0            6
1025 2016-11-26 1970-01-01 10768.0         204
1026 2016-11-27 1970-01-01 9679.0           68
1027 2016-11-28 1970-01-01 6219.0            6
     2016-11-29 1970-01-01 1783.0           36

[346 rows x 1 columns]

In [231]:
    running_sum = result.groupby(level=[0,1,2,3]).sum().groupby(level=[0,1,2]).cumsum()

In [232]:
    running_sum

                                         Money
sid  date       PayTime    peopleCount
1001 2016-11-10 1970-01-01 12353.0          75
                2016-11-10 12353.0      123312
                2016-11-11 12353.0       48985
                2016-11-12 12353.0       22693
                2016-11-13 12353.0       20406
                2016-11-14 12353.0        6595
                2016-11-15 12353.0        8432
                2016-11-16 12353.0        6989
                2016-11-17 12353.0        2042
                2016-11-18 12353.0         522
     2016-11-11 2016-11-11 2088.0         2941
                2016-11-12 2088.0         2802
                2016-11-13 2088.0          831
                2016-11-14 2088.0          438
                2016-11-15 2088.0          666
                2016-11-16 2088.0           14
                2016-11-17 2088.0          135
     2016-11-12 1970-01-01 2169.0            2
                2016-11-12 2169.0         6764
                2016-11-13 2169.0         1282
                2016-11-14 2169.0          663
                2016-11-15 2169.0          647
                2016-11-16 2169.0          215
                2016-11-17 2169.0          332
                2016-11-18 2169.0           80
     2016-11-13 2016-11-13 1394.0         1122
                2016-11-14 1394.0         1023
                2016-11-15 1394.0          543
                2016-11-16 1394.0          318
                2016-11-17 1394.0           67
...                                        ...
1013 2016-11-15 2016-11-16 12914.0       55990
                2016-11-17 12914.0       16209
                2016-11-18 12914.0        1982
     2016-11-16 1970-01-01 3258.0          205
                2016-11-16 3258.0         9304
                2016-11-17 3258.0         4974
                2016-11-18 3258.0          381
     2016-11-17 2016-11-17 61.0            648
                2016-11-18 61.0             99
1014 2016-11-16 1970-01-01 10668.0          90
                2016-11-16 10668.0       53705
                2016-11-17 10668.0       24937
                2016-11-18 10668.0        3147
     2016-11-17 1970-01-01 2968.0            1
                2016-11-17 2968.0        10651
                2016-11-18 2968.0          659
1015 2016-11-17 1970-01-01 9414.0          136
                2016-11-17 9414.0        77134
                2016-11-18 9414.0         3217
     2016-11-18 1970-01-01 2405.0           68
                2016-11-18 2405.0         1226
1016 2016-11-19 1970-01-01 3372.0           18
1020 2016-11-21 1970-01-01 7412.0           69
1021 2016-11-22 1970-01-01 8023.0           68
1022 2016-11-23 1970-01-01 7870.0          136
1024 2016-11-25 1970-01-01 6944.0            6
1025 2016-11-26 1970-01-01 10768.0         204
1026 2016-11-27 1970-01-01 9679.0           68
1027 2016-11-28 1970-01-01 6219.0            6
     2016-11-29 1970-01-01 1783.0           36

[346 rows x 1 columns]

In [268]:
    data2 = result.reset_index()

In [269]:
    data3 = data2.set_index(["sid", "date", "PayTime","peopleCount"])

In [270]:
    data3

                                         Money
sid  date       PayTime    peopleCount
1001 2016-11-10 1970-01-01 12353.0          75
                2016-11-10 12353.0      123312
                2016-11-11 12353.0       48985
                2016-11-12 12353.0       22693
                2016-11-13 12353.0       20406
                2016-11-14 12353.0        6595
                2016-11-15 12353.0        8432
                2016-11-16 12353.0        6989
                2016-11-17 12353.0        2042
                2016-11-18 12353.0         522
     2016-11-11 2016-11-11 2088.0         2941
                2016-11-12 2088.0         2802
                2016-11-13 2088.0          831
                2016-11-14 2088.0          438
                2016-11-15 2088.0          666
                2016-11-16 2088.0           14
                2016-11-17 2088.0          135
     2016-11-12 1970-01-01 2169.0            2
                2016-11-12 2169.0         6764
                2016-11-13 2169.0         1282
                2016-11-14 2169.0          663
                2016-11-15 2169.0          647
                2016-11-16 2169.0          215
                2016-11-17 2169.0          332
                2016-11-18 2169.0           80
     2016-11-13 2016-11-13 1394.0         1122
                2016-11-14 1394.0         1023
                2016-11-15 1394.0          543
                2016-11-16 1394.0          318
                2016-11-17 1394.0           67
...                                        ...
1013 2016-11-15 2016-11-16 12914.0       55990
                2016-11-17 12914.0       16209
                2016-11-18 12914.0        1982
     2016-11-16 1970-01-01 3258.0          205
                2016-11-16 3258.0         9304
                2016-11-17 3258.0         4974
                2016-11-18 3258.0          381
     2016-11-17 2016-11-17 61.0            648
                2016-11-18 61.0             99
1014 2016-11-16 1970-01-01 10668.0          90
                2016-11-16 10668.0       53705
                2016-11-17 10668.0       24937
                2016-11-18 10668.0        3147
     2016-11-17 1970-01-01 2968.0            1
                2016-11-17 2968.0        10651
                2016-11-18 2968.0          659
1015 2016-11-17 1970-01-01 9414.0          136
                2016-11-17 9414.0        77134
                2016-11-18 9414.0         3217
     2016-11-18 1970-01-01 2405.0           68
                2016-11-18 2405.0         1226
1016 2016-11-19 1970-01-01 3372.0           18
1020 2016-11-21 1970-01-01 7412.0           69
1021 2016-11-22 1970-01-01 8023.0           68
1022 2016-11-23 1970-01-01 7870.0          136
1024 2016-11-25 1970-01-01 6944.0            6
1025 2016-11-26 1970-01-01 10768.0         204
1026 2016-11-27 1970-01-01 9679.0           68
1027 2016-11-28 1970-01-01 6219.0            6
     2016-11-29 1970-01-01 1783.0           36

[346 rows x 1 columns]

In [273]:
    data4 = data3.groupby(level= [0,1,2,3]).sum().groupby(level=[0,1,2,3]).cumsum()

In [274]:
    data4

                                         Money
sid  date       PayTime    peopleCount
1001 2016-11-10 1970-01-01 12353.0          75
                2016-11-10 12353.0      123312
                2016-11-11 12353.0       48985
                2016-11-12 12353.0       22693
                2016-11-13 12353.0       20406
                2016-11-14 12353.0        6595
                2016-11-15 12353.0        8432
                2016-11-16 12353.0        6989
                2016-11-17 12353.0        2042
                2016-11-18 12353.0         522
     2016-11-11 2016-11-11 2088.0         2941
                2016-11-12 2088.0         2802
                2016-11-13 2088.0          831
                2016-11-14 2088.0          438
                2016-11-15 2088.0          666
                2016-11-16 2088.0           14
                2016-11-17 2088.0          135
     2016-11-12 1970-01-01 2169.0            2
                2016-11-12 2169.0         6764
                2016-11-13 2169.0         1282
                2016-11-14 2169.0          663
                2016-11-15 2169.0          647
                2016-11-16 2169.0          215
                2016-11-17 2169.0          332
                2016-11-18 2169.0           80
     2016-11-13 2016-11-13 1394.0         1122
                2016-11-14 1394.0         1023
                2016-11-15 1394.0          543
                2016-11-16 1394.0          318
                2016-11-17 1394.0           67
...                                        ...
1013 2016-11-15 2016-11-16 12914.0       55990
                2016-11-17 12914.0       16209
                2016-11-18 12914.0        1982
     2016-11-16 1970-01-01 3258.0          205
                2016-11-16 3258.0         9304
                2016-11-17 3258.0         4974
                2016-11-18 3258.0          381
     2016-11-17 2016-11-17 61.0            648
                2016-11-18 61.0             99
1014 2016-11-16 1970-01-01 10668.0          90
                2016-11-16 10668.0       53705
                2016-11-17 10668.0       24937
                2016-11-18 10668.0        3147
     2016-11-17 1970-01-01 2968.0            1
                2016-11-17 2968.0        10651
                2016-11-18 2968.0          659
1015 2016-11-17 1970-01-01 9414.0          136
                2016-11-17 9414.0        77134
                2016-11-18 9414.0         3217
     2016-11-18 1970-01-01 2405.0           68
                2016-11-18 2405.0         1226
1016 2016-11-19 1970-01-01 3372.0           18
1020 2016-11-21 1970-01-01 7412.0           69
1021 2016-11-22 1970-01-01 8023.0           68
1022 2016-11-23 1970-01-01 7870.0          136
1024 2016-11-25 1970-01-01 6944.0            6
1025 2016-11-26 1970-01-01 10768.0         204
1026 2016-11-27 1970-01-01 9679.0           68
1027 2016-11-28 1970-01-01 6219.0            6
     2016-11-29 1970-01-01 1783.0           36

[346 rows x 1 columns]

In [197]:
    cc = newResult.to_frame(name=None)

In [198]:
    cc

                                          Money
sid  date       PayTime    peopleCount
1001 2016-11-10 1970-01-01 12353.0           75
                2016-11-10 12353.0       123387
                2016-11-11 12353.0       172372
                2016-11-12 12353.0       195065
                2016-11-13 12353.0       215471
                2016-11-14 12353.0       222066
                2016-11-15 12353.0       230498
                2016-11-16 12353.0       237487
                2016-11-17 12353.0       239529
                2016-11-18 12353.0       240051
     2016-11-11 2016-11-11 2088.0        242992
                2016-11-12 2088.0        245794
                2016-11-13 2088.0        246625
                2016-11-14 2088.0        247063
                2016-11-15 2088.0        247729
                2016-11-16 2088.0        247743
                2016-11-17 2088.0        247878
     2016-11-12 1970-01-01 2169.0        247880
                2016-11-12 2169.0        254644
                2016-11-13 2169.0        255926
                2016-11-14 2169.0        256589
                2016-11-15 2169.0        257236
                2016-11-16 2169.0        257451
                2016-11-17 2169.0        257783
                2016-11-18 2169.0        257863
     2016-11-13 2016-11-13 1394.0        258985
                2016-11-14 1394.0        260008
                2016-11-15 1394.0        260551
                2016-11-16 1394.0        260869
                2016-11-17 1394.0        260936
...                                         ...
1013 2016-11-15 2016-11-16 12914.0      2203023
                2016-11-17 12914.0      2219232
                2016-11-18 12914.0      2221214
     2016-11-16 1970-01-01 3258.0       2221419
                2016-11-16 3258.0       2230723
                2016-11-17 3258.0       2235697
                2016-11-18 3258.0       2236078
     2016-11-17 2016-11-17 61.0         2236726
                2016-11-18 61.0         2236825
1014 2016-11-16 1970-01-01 10668.0      2236915
                2016-11-16 10668.0      2290620
                2016-11-17 10668.0      2315557
                2016-11-18 10668.0      2318704
     2016-11-17 1970-01-01 2968.0       2318705
                2016-11-17 2968.0       2329356
                2016-11-18 2968.0       2330015
1015 2016-11-17 1970-01-01 9414.0       2330151
                2016-11-17 9414.0       2407285
                2016-11-18 9414.0       2410502
     2016-11-18 1970-01-01 2405.0       2410570
                2016-11-18 2405.0       2411796
1016 2016-11-19 1970-01-01 3372.0       2411814
1020 2016-11-21 1970-01-01 7412.0       2411883
1021 2016-11-22 1970-01-01 8023.0       2411951
1022 2016-11-23 1970-01-01 7870.0       2412087
1024 2016-11-25 1970-01-01 6944.0       2412093
1025 2016-11-26 1970-01-01 10768.0      2412297
1026 2016-11-27 1970-01-01 9679.0       2412365
1027 2016-11-28 1970-01-01 6219.0       2412371
     2016-11-29 1970-01-01 1783.0       2412407

[346 rows x 1 columns]

In [145]:
    del result['peopleCount']
    del result['sid']
    del result['sid_r']

In [199]:
    cc.reset_index(inplace=True)

In [200]:
    cc

      sid       date     PayTime  peopleCount    Money
0    1001 2016-11-10  1970-01-01      12353.0       75
1    1001 2016-11-10  2016-11-10      12353.0   123387
2    1001 2016-11-10  2016-11-11      12353.0   172372
3    1001 2016-11-10  2016-11-12      12353.0   195065
4    1001 2016-11-10  2016-11-13      12353.0   215471
5    1001 2016-11-10  2016-11-14      12353.0   222066
6    1001 2016-11-10  2016-11-15      12353.0   230498
7    1001 2016-11-10  2016-11-16      12353.0   237487
8    1001 2016-11-10  2016-11-17      12353.0   239529
9    1001 2016-11-10  2016-11-18      12353.0   240051
10   1001 2016-11-11  2016-11-11       2088.0   242992
11   1001 2016-11-11  2016-11-12       2088.0   245794
12   1001 2016-11-11  2016-11-13       2088.0   246625
13   1001 2016-11-11  2016-11-14       2088.0   247063
14   1001 2016-11-11  2016-11-15       2088.0   247729
15   1001 2016-11-11  2016-11-16       2088.0   247743
16   1001 2016-11-11  2016-11-17       2088.0   247878
17   1001 2016-11-12  1970-01-01       2169.0   247880
18   1001 2016-11-12  2016-11-12       2169.0   254644
19   1001 2016-11-12  2016-11-13       2169.0   255926
20   1001 2016-11-12  2016-11-14       2169.0   256589
21   1001 2016-11-12  2016-11-15       2169.0   257236
22   1001 2016-11-12  2016-11-16       2169.0   257451
23   1001 2016-11-12  2016-11-17       2169.0   257783
24   1001 2016-11-12  2016-11-18       2169.0   257863
25   1001 2016-11-13  2016-11-13       1394.0   258985
26   1001 2016-11-13  2016-11-14       1394.0   260008
27   1001 2016-11-13  2016-11-15       1394.0   260551
28   1001 2016-11-13  2016-11-16       1394.0   260869
29   1001 2016-11-13  2016-11-17       1394.0   260936
..    ...        ...         ...          ...      ...
316  1013 2016-11-15  2016-11-16      12914.0  2203023
317  1013 2016-11-15  2016-11-17      12914.0  2219232
318  1013 2016-11-15  2016-11-18      12914.0  2221214
319  1013 2016-11-16  1970-01-01       3258.0  2221419
320  1013 2016-11-16  2016-11-16       3258.0  2230723
321  1013 2016-11-16  2016-11-17       3258.0  2235697
322  1013 2016-11-16  2016-11-18       3258.0  2236078
323  1013 2016-11-17  2016-11-17         61.0  2236726
324  1013 2016-11-17  2016-11-18         61.0  2236825
325  1014 2016-11-16  1970-01-01      10668.0  2236915
326  1014 2016-11-16  2016-11-16      10668.0  2290620
327  1014 2016-11-16  2016-11-17      10668.0  2315557
328  1014 2016-11-16  2016-11-18      10668.0  2318704
329  1014 2016-11-17  1970-01-01       2968.0  2318705
330  1014 2016-11-17  2016-11-17       2968.0  2329356
331  1014 2016-11-17  2016-11-18       2968.0  2330015
332  1015 2016-11-17  1970-01-01       9414.0  2330151
333  1015 2016-11-17  2016-11-17       9414.0  2407285
334  1015 2016-11-17  2016-11-18       9414.0  2410502
335  1015 2016-11-18  1970-01-01       2405.0  2410570
336  1015 2016-11-18  2016-11-18       2405.0  2411796
337  1016 2016-11-19  1970-01-01       3372.0  2411814
338  1020 2016-11-21  1970-01-01       7412.0  2411883
339  1021 2016-11-22  1970-01-01       8023.0  2411951
340  1022 2016-11-23  1970-01-01       7870.0  2412087
341  1024 2016-11-25  1970-01-01       6944.0  2412093
342  1025 2016-11-26  1970-01-01      10768.0  2412297
343  1026 2016-11-27  1970-01-01       9679.0  2412365
344  1027 2016-11-28  1970-01-01       6219.0  2412371
345  1027 2016-11-29  1970-01-01       1783.0  2412407

[346 rows x 5 columns]

In [204]:
    cc['consume'] = cc.Money / cc.peopleCount

In [207]:
    cc

      sid       date     PayTime  peopleCount    Money       consume
0    1001 2016-11-10  1970-01-01      12353.0       75      0.006071
1    1001 2016-11-10  2016-11-10      12353.0   123387      9.988424
2    1001 2016-11-10  2016-11-11      12353.0   172372     13.953857
3    1001 2016-11-10  2016-11-12      12353.0   195065     15.790901
4    1001 2016-11-10  2016-11-13      12353.0   215471     17.442807
5    1001 2016-11-10  2016-11-14      12353.0   222066     17.976686
6    1001 2016-11-10  2016-11-15      12353.0   230498     18.659273
7    1001 2016-11-10  2016-11-16      12353.0   237487     19.225047
8    1001 2016-11-10  2016-11-17      12353.0   239529     19.390351
9    1001 2016-11-10  2016-11-18      12353.0   240051     19.432607
10   1001 2016-11-11  2016-11-11       2088.0   242992    116.375479
11   1001 2016-11-11  2016-11-12       2088.0   245794    117.717433
12   1001 2016-11-11  2016-11-13       2088.0   246625    118.115421
13   1001 2016-11-11  2016-11-14       2088.0   247063    118.325192
14   1001 2016-11-11  2016-11-15       2088.0   247729    118.644157
15   1001 2016-11-11  2016-11-16       2088.0   247743    118.650862
16   1001 2016-11-11  2016-11-17       2088.0   247878    118.715517
17   1001 2016-11-12  1970-01-01       2169.0   247880    114.283080
18   1001 2016-11-12  2016-11-12       2169.0   254644    117.401568
19   1001 2016-11-12  2016-11-13       2169.0   255926    117.992623
20   1001 2016-11-12  2016-11-14       2169.0   256589    118.298294
21   1001 2016-11-12  2016-11-15       2169.0   257236    118.596588
22   1001 2016-11-12  2016-11-16       2169.0   257451    118.695712
23   1001 2016-11-12  2016-11-17       2169.0   257783    118.848778
24   1001 2016-11-12  2016-11-18       2169.0   257863    118.885662
25   1001 2016-11-13  2016-11-13       1394.0   258985    185.785509
26   1001 2016-11-13  2016-11-14       1394.0   260008    186.519369
27   1001 2016-11-13  2016-11-15       1394.0   260551    186.908895
28   1001 2016-11-13  2016-11-16       1394.0   260869    187.137016
29   1001 2016-11-13  2016-11-17       1394.0   260936    187.185079
..    ...        ...         ...          ...      ...           ...
316  1013 2016-11-15  2016-11-16      12914.0  2203023    170.591838
317  1013 2016-11-15  2016-11-17      12914.0  2219232    171.846988
318  1013 2016-11-15  2016-11-18      12914.0  2221214    172.000465
319  1013 2016-11-16  1970-01-01       3258.0  2221419    681.835175
320  1013 2016-11-16  2016-11-16       3258.0  2230723    684.690915
321  1013 2016-11-16  2016-11-17       3258.0  2235697    686.217618
322  1013 2016-11-16  2016-11-18       3258.0  2236078    686.334561
323  1013 2016-11-17  2016-11-17         61.0  2236726  36667.639344
324  1013 2016-11-17  2016-11-18         61.0  2236825  36669.262295
325  1014 2016-11-16  1970-01-01      10668.0  2236915    209.684571
326  1014 2016-11-16  2016-11-16      10668.0  2290620    214.718785
327  1014 2016-11-16  2016-11-17      10668.0  2315557    217.056337
328  1014 2016-11-16  2016-11-18      10668.0  2318704    217.351331
329  1014 2016-11-17  1970-01-01       2968.0  2318705    781.234838
330  1014 2016-11-17  2016-11-17       2968.0  2329356    784.823450
331  1014 2016-11-17  2016-11-18       2968.0  2330015    785.045485
332  1015 2016-11-17  1970-01-01       9414.0  2330151    247.519758
333  1015 2016-11-17  2016-11-17       9414.0  2407285    255.713299
334  1015 2016-11-17  2016-11-18       9414.0  2410502    256.055024
335  1015 2016-11-18  1970-01-01       2405.0  2410570   1002.316008
336  1015 2016-11-18  2016-11-18       2405.0  2411796   1002.825780
337  1016 2016-11-19  1970-01-01       3372.0  2411814    715.247331
338  1020 2016-11-21  1970-01-01       7412.0  2411883    325.402455
339  1021 2016-11-22  1970-01-01       8023.0  2411951    300.629565
340  1022 2016-11-23  1970-01-01       7870.0  2412087    306.491360
341  1024 2016-11-25  1970-01-01       6944.0  2412093    347.363623
342  1025 2016-11-26  1970-01-01      10768.0  2412297    224.024610
343  1026 2016-11-27  1970-01-01       9679.0  2412365    249.237008
344  1027 2016-11-28  1970-01-01       6219.0  2412371    387.903361
345  1027 2016-11-29  1970-01-01       1783.0  2412407   1353.004487

[346 rows x 6 columns]

In [206]:
    

    cc['day'] = (cc['PayTime'].apply(lambda x: x.date())) - result['date'].apply(lambda x: x.date())

    finalResult = cc[['sid', 'date', 'consume', 'day']]
    print finalResult

AttributeError: 'unicode' object has no attribute 'date'

In [233]:
data1=pd.DataFrame({'Dir':['E','E','W','W','E','W','W','E'], 'Bool':['Y','N','Y','N','Y','N','Y','N'], 'Data':[4,5,6,7,8,9,10,11]}, index=pd.DatetimeIndex(['12/30/2000','12/30/2000','12/30/2000','1/2/2001','1/3/2001','1/3/2001','12/30/2000','12/30/2000']))

In [234]:
data1

           Bool  Data Dir
2000-12-30    Y     4   E
2000-12-30    N     5   E
2000-12-30    Y     6   W
2001-01-02    N     7   W
2001-01-03    Y     8   E
2001-01-03    N     9   W
2000-12-30    Y    10   W
2000-12-30    N    11   E

In [263]:
data2 = data1.reset_index()
data3 = data2.set_index(["Bool", "Dir", "index"])   # index is the new column created by reset_index
running_sum = data3.groupby(level=[0,1,2]).sum().groupby(level=[0,1]).cumsum()

In [258]:
data3

                     Data
Bool Dir index
Y    E   2000-12-30     4
N    E   2000-12-30     5
Y    W   2000-12-30     6
N    W   2001-01-02     7
Y    E   2001-01-03     8
N    W   2001-01-03     9
Y    W   2000-12-30    10
N    E   2000-12-30    11

In [264]:
running_sum

                     Data
Bool Dir index
N    E   2000-12-30    16
     W   2001-01-02     7
         2001-01-03    16
Y    E   2000-12-30     4
         2001-01-03    12
     W   2000-12-30    16